lib/mssql/Open-IcingaMSSQLConnection.psm1
=> Feature: Adds support to test MSSQL connections

doc/90-Roadmap.md
Updates roadmap to latest version
=> Doc: Update roadmap with new topics and releases

doc/31-Changelog.md, doc/developerguide/02-New-IcingaCheckPackage.md, lib/icinga/plugin/New-IcingaCheckPackage.psm1
Adds support to ignore empty check packages and return `Ok` instead of `Unknown` if `-IgnoreEmptyPackage` is set on `New-IcingaCheckPackage`
=> Feature: Adds support to ignore empty check packages

doc/31-Changelog.md, icinga-powershell-framework.psd1, icinga-powershell-framework.psm1
Add Cmdlet `Start-IcingaShellAsUser` to open an Icinga Shell as different user for testing
=> Feature: Add Cmdlet to open Icinga Shell as different user

doc/31-Changelog.md, lib/core/tools/Convert-Bytes.psm1, lib/core/tools/Convert-IcingaPluginThresholds.psm1, lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Adds Cmdlet `Convert-IcingaPluginThresholds` as generic approach to convert Icinga Thresholds with units to the lowest unit of this type.
=> Feature: Add generic Cmdlet to convert Icinga Thresholds

doc/31-Changelog.md, lib/core/tools/Get-IcingaUserSID.psm1, lib/core/tools/Split-IcingaUserDomain.psm1, lib/wmi/Add-IcingaWmiPermissions.psm1, lib/wmi/Get-IcingaWindowsInformation.psm1, lib/wmi/Get-IcingaWmiSecurityData.psm1, lib/wmi/Icinga_WBEM_Security.psm1, lib/wmi/New-IcingaWmiPermissionMask.psm1, lib/wmi/Remove-IcingaWmiPermissions.psm1, lib/wmi/Test-IcingaWindowsInformation.psm1, lib/wmi/Test-IcingaWmiPermissions.psm1
You can now use 'Add-IcingaWmiPermissions' to add permissions for a
specific user and namespace and remove them with
'Remove-IcingaWmiPermissions'
=> Feature: Adds support to add/remove/test Wmi permissions

doc/31-Changelog.md, icinga-powershell-framework.psm1
=> Feature: Allow sharing of local variables with Icinga Shell

doc/30-upgrading-framework.md
=> Doc: Adds upgrading notes for plugins and kickstart for v1.3.0

lib/icinga/exception/Exit-IcingaThrowException.psm1
Exception messages were missing the proper category name
=> Fix: Fixes exception output not properly constructed

doc/knowledgebase/IWKB000005.md
Adds UI description for configuring PATH variables besides the PowerShell way.
=> Doc: Adds UI configuration description for path environment variable

doc/31-Changelog.md, lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
=> Fix: Agent installer crash on package lookup with different files in directory

doc/31-Changelog.md, lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Fixes Get-IcingaCheckCommandConfig -IcingaConfig generates invalid configuration file #181
=> Fix: Icinga 2 .conf file generator is generating invalid files

doc/06-Framework-Usage.md, doc/frameworkusage/04-Disable-Certificate-Validation.md
=> Docs: Ignore SSL-Errors documentation

doc/06-Framework-Usage.md, doc/31-Changelog.md, doc/frameworkusage/36-Flush-Icinga-Agent-API-Directory.md, lib/core/icingaagent/misc/Clear-IcingaAgentApiDirectory.psm1
Adds Cmdlet `Clear-IcingaAgentApiDirectory` to flush the entire content of the Icinga Agent API directory locally.
=> Feature: Adds Cmdlet to flush Icinga Agent API directory

doc/31-Changelog.md, lib/core/framework/Uninstall-IcingaForWindows.psm1, lib/core/framework/Uninstall-IcingaFrameworkComponent.psm1
Adds feature to uninstall single components for Icinga for Windows or to uninstall everything and start entirely from new.
=> Feature: Adds support to uninstall Icinga for Windows

lib/core/cache/Set-IcingaCacheData.psm1
experienced on w2k12 r2 with ps version 4.0
=> fixes new-item asking for input type

doc/31-Changelog.md, lib/icinga/exception/Exit-IcingaThrowException.psm1
Improves internal exception handler to get rid if misplaced `:` and adds all fields properly
=> Feature: Rewrite exception handler

lib/core/tools/Show-IcingaEventLogAnalysis.psm1
Improves `Show-IcingaEventLogAnalysis` by properly handling array logs and only processing the first entry while also adding timestamps for the newest and oldest eventog entry
Fixes #246
=> Fix: Array handling on log analyser and adds timestamp to output

lib/icinga/plugin/New-IcingaCheck.psm1
Fixes an issue for Performance Data, which mainly occurs for hidden packages and checks, as there was no action taking place to "use" the provided value in someway. This caused the performance data object not being generated and threfor was not added to the check output.
=> Fix: Performance Data was not written for checks which were not compared to a threshold

doc/31-Changelog.md, lib/core/tools/Convert-IcingaPluginValueToString.psm1, lib/core/tools/Get-IcingaNetworkInterfaceUnits.psm1, lib/icinga/enums/Icinga_IcingaEnums.psm1, lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Adds initial handling for handling link speeds or anything else by using new units and conversions, which were formerly used inside the Network plugin and corresponding provider.
=> Feature: Adds first handling for Framework link speeds

doc/installation/04-Icinga-Agent-Wizard.md
In this change I added info on how to get the ticket number and self service API key.  I think this is useful (possibly essential?) information and doesn't seem to be documented anywhere, so I have submitted this change.  It would have helped me a lot.
Related forum discussion:
https://community.icinga.com/t/icinga-for-windows-self-service-api-key/7490/2
=> Docs: Update 04-Icinga-Agent-Wizard.md

doc/06-Framework-Usage.md, doc/icingaintegration/02-Manual-Integration.md
changed "automaticly" to "automatically"
=> Docs: fix typo on manual integration page 02-Manual-Integration.md

doc/31-Changelog.md, lib/core/tools/Test-IcingaDecimal.psm1, lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Fixes check value conversion to decimal, which sometimes did not resolve values properly and caused conversion issues
Fixes #276
=> Fix: Input value decimal conversion

doc/31-Changelog.md, lib/core/tools/Get-IcingaCheckCommandConfig.psm1
=> Fix: Plain Icinga config generation

doc/31-Changelog.md, lib/core/tools/ConvertTo-Seconds.psm1
=> Fix: Crash on creation of default threshold values

doc/31-Changelog.md, lib/daemons/ServiceCheckDaemon/Start-IcingaServiceCheckDaemon.psm1, lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
Fixes background service check daemon not working with arguments for plugins
Fixes #295
=> Fix: Service check background daemon not working with arguments

doc/31-Changelog.md, lib/core/tools/Convert-IcingaPluginThresholds.psm1
In case negative offsets were processed by the checker handling, in some scenarios this would cause an exception.
Fixes #311
=> Fix: Exception on negative offsets

doc/repositorymanager/01-Add-Existing-Repositories.md, lib/core/repository/Add-IcingaRepository.psm1
Extends repository feature, by allowing to force add new repositories with the same name, overriding current configuration.
=> Feature: Allow force adding of repository

doc/31-Changelog.md, doc/frameworkusage/06-Update-Framework-And-Components.md, doc/frameworkusage/32-Test-Icinga-Agent-Environment.md, doc/frameworkusage/33-Run-Icinga-Agent-As-Other-Service-User.md, lib/core/icingaagent/tests/Test-IcingaAcl.psm1, lib/core/installer/Install-Icinga.psm1, lib/core/installer/menu/installation/general/InstallWindows.psm1, lib/core/installer/menu/installation/general/InstallationConfigString.psm1, lib/core/installer/menu/installation/ifwservice/SelectInstallService.psm1, lib/core/installer/menu/manage/general/ListOverview.psm1, lib/core/installer/tools/ShowInstallerMenu.psm1, lib/core/logging/Write-IcingaConsoleOutput.psm1, lib/core/logging/Write-IcingaConsolePlain.psm1, lib/core/repository/Get-IcingaRepositoryPackage.psm1, lib/core/repository/Search-IcingaRepository.psm1, lib/core/repository/Show-Icinga.psm1, lib/core/tools/Add-IcingaWhiteSpaceToString.psm1, lib/core/tools/Write-IcingaConsoleHeader.psm1, lib/core/tools/Write-IcingaConsoleTextColorSplit.psm1
Fixes plenty of spelling mistakes, style guides, views, layouts and other visual topics for the Icinga for Windows Management Console.
=> Style: Adds mmc list view, kickstart filter, spelling fix

lib/core/installer/menu/manage/framework/ManageFramework.psm1, lib/core/installer/menu/manage/framework/repository/ManageIcingaRepo.psm1, lib/core/installer/menu/manage/framework/repository/SetIcingaSnapshotRepo.psm1, lib/core/installer/menu/manage/framework/repository/SetIcingaStableRepo.psm1, lib/core/installer/tools/AddConfigEntry.psm1, lib/core/installer/tools/ShowInstallerMenu.psm1
Adds repository management to the Icinga Management Console
=> Feature: Adds repo management to imc

lib/core/installer/Install-Icinga.psm1, lib/core/installer/menu/installation/director/DirectorTemplate.psm1, lib/core/installer/menu/installation/director/DirectorUrl.psm1, lib/core/installer/menu/installation/general/FinishInstaller.psm1, lib/core/installer/menu/installation/icinga/SelectConnection.psm1
Adds various fixes and improvements for the Icinga Director Self-Service API while using IMC.
=> Fix: Various issues with Icinga Director on IMC

doc/31-Changelog.md, lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1, lib/core/installer/Install-Icinga.psm1, lib/core/installer/menu/installation/general/ConfigurationSummary.psm1, lib/core/installer/menu/manage/framework/repository/SetIcingaSnapshotRepo.psm1, lib/core/installer/menu/manage/framework/repository/SetIcingaStableRepo.psm1, lib/core/installer/menu/manage/general/RemoveComponents.psm1, lib/core/installer/tools/ShowInstallerMenu.psm1, lib/core/installer/tools/Write-IcingaManagementConsoleCommand.psm1, lib/core/tools/Get-IcingaCheckCommandConfig.psm1, lib/wmi/Add-IcingaWmiPermissions.psm1
Added vartious improvements to IMC, which allows a better view on the final summary form. In addition, we provide now the following new features:
* Show commands being executed inside IMC with `l`
* Use placeholder `$DefaultValues$` inside actions, to call commands directly for actions and replace `$DefaultValues$` with the value the user added into the form
=> Feature: Adds improvements to IMC including cmd preview

lib/core/repository/Read-IcingaRepositoryFile.psm1
If a website is delivering content, the repository validation might have failed because of invalid JSON content. The new resolver will now fix the lookup, the error message and tries another attempt with a direct access to `ifw.repo.json` in case the first attempt failed due to HTTP errors or invalid repo content provided.
=> Fix: Repository resolving and validation

doc/31-Changelog.md, lib/icinga/enums/Icinga_IcingaEnums.psm1, lib/webserver/New-IcingaTCPClientRESTMessage.psm1, lib/webserver/Read-IcingaTCPStream.psm1
Improves debugging output on TCP handling, to provide separate messages for incoming message size, message bytes and the send message back to the client.
=> Feature: Improves debug output on TCP handling

doc/repositorymanager/02-Sync-Repositories.md, lib/core/repository/Sync-IcingaRepository.psm1
Adds switch `-SkipSCPMkdir` to `Sync-IcingaRepository`, allowing to skip directory creation.
=> Feature: Adds switch to skip mkdir on scp repo sync

doc/100-General/10-Changelog.md, lib/core/tools/Get-IcingaUserSID.psm1, lib/core/windows/New-IcingaWindowsUser.psm1, lib/core/windows/Remove-IcingaWindowsUser.psm1, lib/core/windows/Test-IcingaManagedUser.psm1, lib/core/windows/Update-IcingaServiceUser.psm1
Fixes a long lookup for the user table on environments with a large Active Directory.
=> Fix: Long lookup for users on large AD

doc/100-General/10-Changelog.md, lib/apis/Get-IcingaDirectorSelfServiceConfig.psm1, lib/apis/Get-IcingaDirectorSelfServiceTicket.psm1, lib/apis/Register-IcingaDirectorSelfServiceHost.psm1, lib/core/icingaagent/misc/Start-IcingaAgentDirectorWizard.psm1, lib/core/installer/Install-Icinga.psm1, lib/core/installer/Start-IcingaForWindowsInstallation.psm1, lib/core/installer/menu/installation/director/DirectorTemplate.psm1, lib/core/installer/tools/ShowInstallerMenu.psm1, lib/core/logging/Write-IcingaConsoleDebug.psm1, lib/core/logging/Write-IcingaConsoleError.psm1, lib/core/logging/Write-IcingaConsoleNotice.psm1, lib/core/logging/Write-IcingaConsoleOutput.psm1, lib/core/logging/Write-IcingaConsolePlain.psm1, lib/core/logging/Write-IcingaConsoleWarning.psm1, lib/web/Invoke-IcingaWebRequest.psm1
Fixes error message handling for Icinga Director while using IMC.
=> Fix: Improves error handling on IMC for Director

doc/100-General/10-Changelog.md, lib/core/framework/Enable-IcingaFrameworkApiChecks.psm1
Removes experimental warning for Api-Check Forwarder feature and adds link to docs.
=> Fix: Removes experimental warning for api check feature

doc/100-General/10-Changelog.md, lib/core/framework/Read-IcingaForWindowsLog.psm1, lib/core/framework/Read-IcingaWindowsEventLog.psm1, lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
Adds generic reader function `Read-IcingaWindowsEventLog`, allowing to read any EventLog as stream on the console and adds in addition `Read-IcingaForWindowsLog` for reading Icinga for Windows specific logs
=> Feature: Adds generic EventLog reader and IfW reader

doc/100-General/10-Changelog.md, lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Adds new function `Publish-IcingaPluginDocumentation` which was previously only available within the plugins package.
=> Feature: Adds function to create plugin documentation

doc/100-General/10-Changelog.md, lib/core/logging/Get-IcingaExceptionString.psm1, lib/core/logging/Write-IcingaDebugMessage.psm1, lib/core/logging/Write-IcingaEventMessage.psm1
Adds a new feature to EventLog writer, allowing to parse an exception report to identity the exact root cause and location, on where the error occurred in first place.
=> Feature: Adds exception report

.gitignore
Updates .gitignore to ignore Visual Studio files
=> Feature: Updates .gitignore for Visual Studio

doc/100-General/10-Changelog.md, lib/core/installer/Start-IcingaForWindowsInstallation.psm1, lib/core/installer/menu/installation/AdvancedEntries.psm1, lib/core/installer/menu/installation/framework/InstallApiChecks.psm1
Adds the support for enabling the Rest-Api including the Api-Check by running the IMC installation.
=> Feature: Adds Rest-Api check forwarder to IMC wizard

doc/100-General/10-Changelog.md, doc/900-Developer-Guide/00-General.md, lib/core/framework/New-IcingaEnvironmentVariable.psm1, lib/core/perfcounter/Add-IcingaPerformanceCounterCache.psm1, lib/core/perfcounter/Get-IcingaPerformanceCounterCacheItem.psm1, lib/core/perfcounter/New-IcingaPerformanceCounterArray.psm1
Moves PerformanceCounter to private space from previous public, which caused some problems.
=> Fix: Moves PerformanceCounter to private space

doc/100-General/10-Changelog.md, lib/core/icingaagent/installer/Repair-IcingaService.psm1, lib/core/icingaagent/setters/Set-IcingaAgentServiceUser.psm1, lib/core/repository/Install-IcingaComponent.psm1
Fixes unhandled `true` output on the console while running the installer
=> Fix: Unhandled true output during installation

lib/core/repository/Show-Icinga.psm1, lib/daemon/Get-IcingaForWindowsServicePid.psm1
Adds pid information to Show-Icinga and improves Icinga for Windows certificate output.
=> Feature: Adds PID to Show-Icinga

doc/100-General/10-Changelog.md, lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Adds table view for plugins with short summary of what the plugin is for and allows multi-lines in example docs
=> Feature: Improves plugin doc generator for better docs

doc/110-Installation/30-API-Check-Forwarder.md
Updates doc for new IMC installation way and removes no longer required dependencies.
=> Doc: REST-Api section doc update

lib/core/framework/Install-IcingaFrameworkComponent.psm1, lib/core/framework/Install-IcingaFrameworkUpdate.psm1, lib/core/framework/Restart-IcingaService.psm1, lib/core/framework/Start-IcingaService.psm1, lib/core/framework/Stop-IcingaService.psm1, lib/core/icingaagent/installer/Install-IcingaAgent.psm1, lib/core/icingaagent/installer/Uninstall-IcingaAgent.psm1, lib/core/repository/Install-IcingaComponent.psm1
=> Fix: Console freezes on Windows 2012 R2 during IMC installation

doc/100-General/10-Changelog.md, lib/core/installer/Start-IcingaForWindowsInstallation.psm1, lib/core/installer/menu/installation/AdvancedEntries.psm1, lib/core/installer/menu/installation/framework/ServiceRecovery.psm1, lib/core/installer/menu/manage/settings/services/ManageServices.psm1, lib/core/windows/Disable-IcingaServiceRecovery.psm1, lib/core/windows/Enable-IcingaServiceRecovery.psm1
Adds support to set service recovery for the Icinga Agent and Icinga for Windows service, to restart them in case of a crash or error
Fixes #40
=> Feature: Adds support for service recovery

icinga-powershell-framework.psm1, templates/compilation.psm1.template
Adds support for the developer mode to now include the modules as well and ensure, that available cache files are overwritten with the template again.
This ensures that we can develop new features and test them on the fly, without having to manipulate cache files manually.
=> Feature: Adds developer mode for components

doc/100-General/10-Changelog.md, lib/core/tools/Test-IcingaArrayFilter.psm1
Adds generic function for easier managing include/exclude filtering for plugins and for cleaning arrays with not wanted content.
=> Feature: Adds function for easier include/exclude filtering

doc/110-Installation/01-Getting-Started.md
Makes installation example for using custom repositories and director automation more clear and fixes missing `IfW-StableRepository` installation command entry.
Fixes #530
=> Docs: Fixes doc for custom repo example installation

doc/110-Installation/04-Installation-Templates.md, lib/core/installer/menu/installation/general/InstallationFileExport.psm1
=> Docs: Fixes wrong argument on Install-Icinga from file

lib/core/repository/Update-IcingaRepository.psm1
Missing commit for #548
Fixes #545
=> Fix: Remote Sync clears RemoteSource

doc/100-General/10-Changelog.md, lib/core/framework/Get-IcingaCheckSchedulerPerfData.psm1, lib/core/framework/Get-IcingaCheckSchedulerPluginOutput.psm1, lib/core/framework/Invoke-IcingaForWindowsMigration.psm1, lib/core/framework/Invoke-IcingaInternalServiceCall.psm1, lib/core/perfcounter/Get-IcingaPerformanceCounterDetails.psm1, lib/core/tools/ConvertTo-IcingaNumericTimeIndex.psm1, lib/core/tools/Format-IcingaPerfDataLabel.psm1, lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1, lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1, lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1, lib/icinga/plugin/New-IcingaCheck.psm1, lib/icinga/plugin/New-IcingaCheckPackage.psm1, lib/icinga/plugin/New-IcingaCheckResult.psm1, lib/icinga/plugin/New-IcingaPerformanceDataEntry.psm1, lib/icinga/plugin/Write-IcingaPluginOutput.psm1, lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
Performance data should be created with some more adjustments to ensure we can properly create graphcs by using InfluxDB and Grafana as example
Fixes #485
=> Feature: Rewrite PerfData Labels for multi output

lib/core/tools/Convert-Bytes.psm1
Fixes byte unit Icinga threshold exception
=> Fix: Byte unit Icinga threshold exception

doc/100-General/10-Changelog.md, lib/icinga/enums/Get-IcingaProviderEnumData.psm1
Adds feature to securely read enum provider values
```powershell
Get-IcingaProviderEnumData -Enum $ProviderEnums -Key 'DiskBusType' -Index 6;
Fibre Channel
```
=> Feature: Adds function to securely read enum provider values

doc/100-General/10-Changelog.md, lib/core/icingaagent/setters/Set-IcingaAgentServiceUser.psm1
Adds support to provide the Icinga service user written as `user@domain`
Fixes #623
=> Feature: Adds support to provide user and domain with @ separated

doc/110-Installation/01-Getting-Started.md, doc/130-JEA/01-JEA-Profiles.md
=> Link to docs.microsoft.com/en-us, not docs.microsoft.com/de-de

doc/100-General/10-Changelog.md, lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1, lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1, lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Fixes some memory management while using the REST-Api to clear connection objects once they are no longer required
=> Fix: Improves REST-Api memory management

doc/100-General/10-Changelog.md, lib/core/repository/New-IcingaRepositoryFile.psm1, lib/core/repository/Sync-IcingaRepository.psm1
Adds support to write the name of the repository synced/created into the local `ifw.repo.json` file
Fixes #572
=> Feature: Adds support to write the name of the repo inside the json file

doc/110-Installation/30-API-Check-Forwarder.md
=> Docs: Improves API forwarder documentation

doc/130-JEA/01-JEA-Profiles.md
Changed the word "Cmldet" to "Cmdlet"
=> Fix typo in 01-JEA-Profiles.md

doc/100-General/10-Changelog.md, doc/111-Updates-and-Uninstallation/01-Update-Environment.md, lib/core/repository/Update-Icinga.psm1
Added a `-Version` parameter to the `Update-Icinga` command, to be able to update a component to a specified version.
Also updated the docs.
=> added -Version parameter to the Update-Icinga` command

doc/100-General/10-Changelog.md, jobs/GetWindowsService.ps1, jobs/RenewCertificate.ps1, jobs/RestartWindowsService.ps1, jobs/StartWindowsService.ps1, jobs/StopWindowsService.ps1, lib/core/framework/Invoke-IcingaForWindowsMigration.psm1, lib/core/framework/Uninstall-IcingaForWindows.psm1, lib/core/installer/Start-IcingaForWindowsInstallation.psm1, lib/core/wintasks/Invoke-IcingaWindowsScheduledTask.psm1, lib/core/wintasks/Invoke-IcingaWindowsServiceHandlerTask.psm1, lib/core/wintasks/Wait-IcingaWindowsScheduledTask.psm1, lib/core/wintasks/daemon/Register-TaskRenewCertificate.psm1, lib/core/wintasks/daemon/Start-TaskRenewCertificate.psm1, lib/core/wintasks/daemon/Unregister-TaskRenewCertificate.psm1
Adds new handling to add scheduled tasks in Windows for interacting with Icinga for Windows core functionality as well as an auto renewal task for the Icinga for Windows certificate generation
=> Feature: Adds handling to add scheduled task background task

doc/100-General/10-Changelog.md, lib/icinga/plugin/New-IcingaCheck.psm1, lib/icinga/plugin/New-IcingaCheckBaseObject.psm1, lib/icinga/plugin/New-IcingaCheckPackage.psm1
Adds support for check objects not being added to summary header
=> Feature: Adds support for check objects not being added to summary header

doc/100-General/10-Changelog.md, doc/110-Installation/02-Icinga-Management-Console.md, doc/110-Installation/03-Installation-with-IMC.md, icinga-powershell-framework.psd1, lib/core/jea/Deny-IcingaJEACommand.psm1, lib/core/jea/Get-IcingaCommandDependency.psm1, lib/core/jea/Get-IcingaFrameworkDependency.psm1, lib/core/jea/Get-IcingaJEAConfiguration.psm1, lib/core/jea/Read-IcingaPowerShellModuleFile.psm1, templates/IcingaForWindows.psrc.template
Adds security hardening to JEA profiles by always prohibit certain cmdlets
=> Feature: Adds security hardening to JEA profiles by always prohibit certain cmdlets

doc/100-General/10-Changelog.md, doc/300-Knowledge-Base.md, doc/knowledgebase/IWKB000017.md
Adds IWKB entry `IWKB000017` handling issues with failed checks once SCOM is uninstalled as example
Fixes #313
=> Docs: Adds IWKB entry `IWKB000017` handling issues with failed checks once SCOM is uninstalled

doc/100-General/10-Changelog.md, lib/core/framework/Publish-IcingaPluginDocumentation.psm1, lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Adds feature to use pipes and multi lines for plugin documentation
=> Feature: Adds support to use pipes and multi lines for plugin documentation

doc/100-General/10-Changelog.md, jobs/RenewCertificate.ps1, lib/core/framework/Invoke-IcingaForWindowsMigration.psm1, lib/core/icingaagent/tests/Test-IcingaForWindows.psm1, lib/core/logging/Icinga_EventLog_Enums.psm1, lib/webserver/Import-IcingaCAToAuthRoot.psm1, lib/webserver/Invoke-IcingaForWindowsRESTApi.psm1, lib/webserver/Test-IcingaCAInstalledToAuthRoot.psm1, lib/webserver/Test-IcingaForWindowsCertificate.psm1
Adds new command `Invoke-IcingaForWindowsRESTApi` for easier API communication with Icinga for Windows
=> Feature: Adds support to authenticate with the Icinga for Windows certificate for the REST-Api

doc/100-General/10-Changelog.md, lib/core/framework/Get-IcingaCheckSchedulerPerfData.psm1, lib/core/framework/Invoke-IcingaInternalServiceCall.psm1, lib/core/framework/New-IcingaEnvironmentVariable.psm1, lib/core/tools/Convert-IcingaPluginThresholds.psm1, lib/core/tools/Convert-IcingaPluginValueToString.psm1, lib/icinga/enums/Icinga_IcingaEnums.psm1, lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1, lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1, lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1, lib/icinga/plugin/Convert-IcingaPluginThresholdsFromPercent.psm1, lib/icinga/plugin/New-IcingaCheck.psm1, lib/icinga/plugin/New-IcingaCheckBaseObject.psm1, lib/icinga/plugin/New-IcingaCheckPackage.psm1, lib/icinga/plugin/Write-IcingaPluginPerfData.psm1, lib/icinga/plugin/Write-IcingaPluginResult.psm1
Reworks the internal handling on how plugin thresholds are evaluated and the internal checker core, including on how performance metrics are generated
=> Rework: Plugin and checker core handling for plugin evaluation

doc/100-General/10-Changelog.md, lib/core/icingaagent/writers/Write-IcingaAgentEventLogConfig.psm1
Fixes an exception for the windowseventlog feature of the Icinga Agent, in case it is not installed.
=> Fix: Icinga Agent exception for windowseventlog feature

doc/100-General/10-Changelog.md, lib/core/perfcounter/New-IcingaPerformanceCounterArray.psm1
Fixes CPU and other performance data metrics to report proper values
=> Fix: CPU performance data exceeding 150%

lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Corrects the link for rendering for to the docs for Metrics over Time
=> Fix: Docs creation for MoT handling with -ThresholdInterval argument

doc/100-General/10-Changelog.md, jobs/GetWindowsService.ps1
Fixes Icinga for Windows service installation not working properly on certain Windows environments
Fixes #780
=> Fix: IfW service installation on certain Windows environment
