Icinga/icinga-powershell-framework

- lib/core/icingaagent/setters/Set-IcingaAgentServiceUser.psm1
Added a space to fix sc.exe not changing user on Windows Server 2008 because it expects a space between 'password=' and '"{2}"'
> Fixed: ServiceUser can't be changed on Server 2008

- lib/core/icingaagent/installer/Install-IcingaAgent.psm1
If the check ((Test-Path $InstallDir) -eq $FALSE) is negative, i.e. the directory 'InstallDir' already exists, 'InstallDir' is not taken.
There are several reasons, for example a new installation, which require that the directory exists. Provided that custom checks were previously installed in 'InstallDir'.
Moving the setting of 'InstallTarget' outside the path check / directory creation ensures that 'InstallDir' is taken care of if the check is negative.
> fix Problem with existing 'InstallDir' while running Install-IcingaAgent

- doc/31-Changelog.md
- lib/mssql/Open-IcingaMSSQLConnection.psm1
While using `IntegratedSecurity` for authentication, the error message printed in case the connection is not possible is stating invalid credentials instead of connection not possible
> Fixes MSSQL error handling on Integrated Security

- doc/31-Changelog.md
- lib/core/framework/Start-IcingaTimer.psm1
`Start-IcingaTiemer` is using `System.Reflection.Assembly` which creates an yet uncatched return value.
> Fixes uncatched invisible output on Start-IcingaTimer

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
Fix crash while running services as background task to collect metrics over time by missing Performance Counter cache initialisation.
Fixes #129
> Bugfix: Fix crash on background service execution caused by missing Perf Data cache

- doc/31-Changelog.md
- lib/core/tools/Convert-Bytes.psm1
Fixes an issue while converting data size values from any other datatype to bytes which will cause an overflow and might result in issues during comparison.
> Bugfix: Fixing value overflow on Convert-Bytes Cmdlet

- doc/31-Changelog.md
- lib/core/framework/Get-IcingaPowerShellModuleVersion.psm1
Fixes version fetching for not loaded modules during upgrades/plugin calls with `Get-IcingaPowerShellModuleVersion`
> Fix: Version fetching for not loaded modules is impossible

- PSScriptAnalyzerSettings.psd1
- doc/31-Changelog.md
Because the script analyzer often complains that we can always use the
function open brace on the same line as the function name, which is not
the case, I finally decided to correct this today. I set the attribute
OnSameLine to False and disabled the check for space before open Brace.
> Disable OnSameLine & don't check space before open brace

- doc/31-Changelog.md
- lib/core/framework/Test-IcingaWindowsInformation.psm1
- lib/core/tools/Test-IcingaBinaryOperator.psm1
- lib/icinga/enums/Test-IcingaWindowsInfoEnums.psm1
- lib/icinga/exception/Get-IcingaLastExceptionId.psm1
Tests if a specific WMI class including the Namespace can be accessed and returns status codes for possible errors/exceptions taht might occure. Returns binary operator values for easier comparison. In case no errors occured it will return $TestIcingaWindowsInfoEnums.TestIcingaWindowsInfo.Ok.
> Check whether or not WMI class exists

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaNetworkInterface.psm1
- lib/core/tools/Get-IcingaNetworkRoute.psm1
Author: @LordHepipud
Tasks @LordHepipud:
Testing:
```powershell
powershell -C { Use-Icinga; Get-IcingaNetworkInterface <icinga_server> }
```
Replace `<icinga_server>` with the IP / FQDN of your Icinga 2 Master / Satellite and check if the correct IP of your local interface is returned which should be added to Icinga 2 for monitoring and connecting.
> Bugfix: Handle multiple network interfaces on discovery and add support for Windows 2008 R2

- doc/31-Changelog.md
- lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
Fixes Icinga Agent API being wrongly disabled after successful certificate configuration and installation
Fixes #114
> Fix: Icinga API being disabled after successfull certificate installation

- doc/31-Changelog.md
- lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
Fixes an issue while changing the hostname between upper/lower case which might cause unwanted exceptions on one hand but also required manual signing of requests on the CA master as the signing process was not completed
> Fix: SSL creation on reconfigure might fail if naming changed from upper/lower case

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Empty arrays will now properly be rendered as empty array with `@()`instead of `$null`. In addition the config renderer now also supports ValidateSet for array entries
> Fix: Array handling for ValidateSet and array rendering for config generator

- doc/31-Changelog.md
- lib/wmi/Get-IcingaWindowsInformation.psm1
Adds support to write all objects collected by `Get-IcingaWindowsInformation` into the Windows EventLog in case the debug output for the Icinga PowerShell Framework is enabled.
> Feature: Add debug output for Get-IcingaWindowsInformation calls to EventLog

- doc/knowledgebase/IWKB000001.md
Updates documentation for possible requirement to restart Wmi service `Winmgmt` to apply permission changes.
> Doc: Updates WMI KB for Winmgmt service restart

- doc/31-Changelog.md
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
Fixes a crash during the update process of the Icinga PowerShell Framework which is caused by a new Cmdlet to write the Icinga Framework code cache, which might not yet be available on the system.
> Fix: Fixes crash during update due to code cache feature

- lib/core/framework/Get-IcingaPowerShellModuleArchive.psm1
Installing IcingaPowerShell components fails with new web method for release packages
> Fix: Instaling PowerShell components fails for release branch

- doc/31-Changelog.md
- doc/icingaintegration/50-Windows-Terminal.md
Adds `exit` after calling `icinga` on Windows Terminal integration to ensure the shell will close in case the Icinga shell is closed.
> Feature: Adds exit to Windows Terminal integration to close shell on exit

- doc/31-Changelog.md
- lib/core/icingaagent/getters/Get-IcingaAgentHostCertificate.psm1
Fixes fetching for Icinga Agent certificate for REST-Api daemon on upper/lower case hostname mismatch
> Fix: Fixes fetching for Icinga Agent certificate for REST-Api daemon on upper/lower case hostname mismatch

- doc/31-Changelog.md
- lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
Fixes fetching of Icinga Agent MSI packages by correctly comparing versions to ensure we always use the latest version  and fixes `release` usage for local/network drive sources.
> Fix: Fixes release fetching of Agent with correct comparison and proper support for local sources

- doc/31-Changelog.md
- lib/core/logging/Write-IcingaEventMessage.psm1
In rare cases it can happen that the EventLog writer will throw an error in case the message size for EventLog entries is too large. This mostly happens in case the debug mode is enabled which is writing plenty of content into the EventLog.
This fix will now split such message into multiple messages to resolve the issue and keeping the data.
> Fix: Fixes error while writing EventLog entries with too large message size

- doc/31-Changelog.md
- lib/core/icingaagent/writers/Write-IcingaAgentZonesConfig.psm1
As we ask the questions for adding `director-global` and `global-templates`, we should leave the decision to the user if these zones should be added by default and not enforce them.
> Fix: Removes hardcoded global zones

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaUnixTime.psm1
Adds support to add milliseconds to the result of `Get-IcingaUnixTime` which might come in handy for more time depending tasks.
> Feature: Add optional support for adding milliseconds to Get-IcingaUnixTime

- doc/31-Changelog.md
- lib/core/framework/Get-IcingaFrameworkServiceBinary.psm1
> Fix backslashes in the url path causes an error

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
In some cases progress bar output for certain activities might be printed into the plugin output. The best option is to disable it entirely while using Icinga for Windows, as we have no use for it.
Fixes #185
> Fix: Disables PowerShell Progress bar while using Icinga for Windows

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaServices.psm1
- lib/icinga/enums/Icinga_IcingaEnums.psm1
In some cases, it can happen that `Get-Service` which is used primarily to fetch most of the service data, is not providing any results of the startup type of the service. This results in an error on the plugin, as the monitoring of all services which should be running `Automatic` and throw a critical if not exited properly is no longer possible. The result is simply "Ok" with no services checked as the status code is always 0 for all services and not matching the actual comparison value of 2 (Automatic)
> Fix: Prefer startup type of services fetching over WMI instead of Get-Services

- doc/06-Framework-Usage.md
- doc/31-Changelog.md
- doc/frameworkusage/05-Enable-Framework-Code-Caching.md
- icinga-powershell-framework.psm1
- lib/core/framework/Disable-IcingaFrameworkCodeCache.psm1
- lib/core/framework/Enable-IcingaFrameworkCodeCache.psm1
- lib/core/framework/Get-IcingaFrameworkCodeCache.psm1
Removes experimental state of the Icinga PowerShell Framework code caching and adds docs on how to use the feature.
> Adds code caching docs and removes experimental

- doc/31-Changelog.md
- lib/core/framework/Get-IcingaCheckSchedulerPerfData.psm1
- lib/core/framework/Get-IcingaCheckSchedulerPluginOutput.psm1
- lib/core/framework/New-IcingaCheckSchedulerEnvironment.psm1
- lib/daemons/ServiceCheckDaemon/Start-IcingaServiceCheckDaemon.psm1
- lib/icinga/plugin/Write-IcingaPluginOutput.psm1
- lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
In case multitple background daemons are running and executing check plugins, it can happen that results overlap from one thread to another. A CPU check might then include information from another service check for example.
We fix this by locking each check result data into an own thread, preventing other threads from accessing the data.
> Feature: Ensure thread results are separated from each other by default

- doc/31-Changelog.md
- icinga-powershell-framework.psd1
- lib/config/Read-IcingaPowerShellConfig.psm1
- lib/core/tools/Read-IcingaFileContent.psm1
In some cases it can happen that multiple processes access our config file. By default `Get-Content` is not thread save and might result in errors while reading the file content.
In general we should use a read-only attempt for the config.json and write it only if required.
> Feature: Ensure config.json is opened as read-only

- doc/31-Changelog.md
- lib/core/cache/Get-IcingaCacheData.psm1
- lib/core/cache/Set-IcingaCacheData.psm1
- lib/core/framework/Clear-IcingaCheckSchedulerCheckData.psm1
- lib/core/framework/Clear-IcingaCheckSchedulerEnvironment.psm1
- lib/core/framework/Get-IcingaCheckSchedulerCheckData.psm1
- lib/core/framework/New-IcingaCheckSchedulerEnvironment.psm1
- lib/daemons/ServiceCheckDaemon/Start-IcingaServiceCheckDaemon.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
Improves the background daemon by separating each single configured check into an own data pool, preventing data of leaking from one thread to another which might cause a memory leak in long term with plenty of background checks defined.
This might also reduce CPU impact because lesser data has to be processed.
> Fix: Background service check daemon data pool separation and memory leak

- doc/31-Changelog.md
- doc/developerguide/01-New-IcingaCheck.md
- lib/icinga/plugin/New-IcingaCheck.psm1
Adds new Argument `-LabelName` to `New-IcingaCheck`, allowing the developer to provide custom label names for checks and override the default based on the check name.
> Adds feature to customize label for checks

- doc/31-Changelog.md
- lib/core/tools/Convert-IcingaPluginThresholds.psm1
Fixes `Convert-IcingaPluginThresholds` which sometimes did not return proper numeric usable values for our internal functions, causing issues on plugin calls. In addition the function now also supports the handling for % units.
> Fix: Plugin threshold conversion and adds % unit handling

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Updates the Icinga DSL for building PowerShell arrays to ensure all string values are properly escaped with `'`. In case the user already wrapped commands with `'` by himself, this will not have an effect as we only add single quotes for escaping if they are not present already.
> Fixes DSL for building array elements escaped

- doc/31-Changelog.md
- icinga-powershell-framework.psd1
- icinga-powershell-framework.psm1
- lib/core/framework/Add-IcingaFrameworkApiCommand.psm1
- lib/core/framework/Disable-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Enable-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Get-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/core/framework/Remove-IcingaFrameworkApiCommand.psm1
- lib/core/framework/Test-IcingaFrameworkApiCommand.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
- lib/core/tools/Add-IcingaArrayListItem.psm1
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
- lib/daemon/Get-IcingaBackgroundDaemons.psm1
- lib/icinga/enums/Icinga_IcingaEnums.psm1
- lib/icinga/exception/Exit-IcingaThrowException.psm1
- lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
- lib/webserver/Enable-IcingaUntrustedCertificateValidation.psm1
Adds experimental feature to forward checks executed by the Icinga Agent to an internal REST-Api, to reduce the performance impact on systems with lower ressources available
> Experimental: Adds experimental feature for internal API checks

- doc/31-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Unknown checks for the plugin handler were called to soon, as the minimal configuration does not load old check commands for the plugins.
In addition API checks did not throw an unknown and were not catched properly
> Fix wrong plugin not installed unknown checkresult

- doc/31-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
Fixes wrong used variable for API call checks.
> Fix: Wrong variable used for API check request

- doc/31-Changelog.md
- icinga-powershell-framework.psd1
With updating Icinga for Windows to v1.4.0, there is an issue with plugins using [Secure.String] variables. By default, we convert string values with the function `ConvertTo-IcingaSecureString` to a [Secure.String] for PowerShell for better usage. Because of the plugin execution change, this function is no longer available with `Use-Icinga -Minimal`
This only affects environments with udpated configuration
Fixes #222
> Fix: ConvertTo-IcingaSecureString exceptions because of not being pre-loaded

- doc/31-Changelog.md
- lib/core/logging/Write-IcingaConsoleOutput.psm1
- lib/daemons/ServiceCheckDaemon/Start-IcingaServiceCheckDaemon.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes "memory leak" on background daemon for registered service checks, by clearing the error stack and manually calling the PowerShell garbage collector to force the freeing of memory.
In addition background daemon tasks will no longer be able to write any information to consoles to keep memory clean as well.
Fixes #224
> Fix: Memory leak on background service daemon

- doc/31-Changelog.md
- lib/icinga/exception/Exit-IcingaThrowException.psm1
Allows to add a custom exception list hashtable to `Exit-IcingaThrowException` for better usability on different modules.
> Adds support to allow custom exception lists

- doc/31-Changelog.md
- lib/core/tools/Show-IcingaEventLogAnalysis.psm1
Adds new Cmdlet `Show-IcingaEventLogAnalysis` to get a better overview on how many log entries are present within the EventLog based on hour, minute and day average/maximum for allowing a more dynamic configuration for `Invoke-IcingaCheckEventLog`
> Adds Cmdlet for analysing EventLog content

- doc/30-upgrading-framework.md
- doc/31-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Adds feature to mask CustomField input values with `*` within the Icinga Director, in case the argument is defined as `SecureString`. Please ensure to read the [upgrading docs](https://icinga.com/docs/icinga-for-windows/latest/doc/30-upgrading-framework/) carefully, before importing new configurations.
Fixes #229
> Feature: Hide SecureString CustomFields input in Icinga Director

- doc/31-Changelog.md
- lib/core/tools/Get-IcingaServices.psm1
While filtering for certain services with `Get-IcingaServices`, there were some attributes missing from the collection. These are now added resulting in always correct output data.
> Fix: Adds missing attributes for services

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
- lib/icinga/plugin/Write-IcingaPluginOutput.psm1
Adds feature to suppress any kind of console output except for plugin output and performance data, while Icinga for Windows is initialised with `Use-Icinga -Minimal`
> Feature: Suppress other messages then plugin output

- doc/31-Changelog.md
- lib/core/perfcounter/Test-IcingaPerformanceCounterCategory.psm1
This will improve `Test-IcingaPerformanceCounterCategory` by creating an object for the Performance Counter category provided and checking if it is a valid object instead of relying on the registry which might not contain all categories in the correct language.
> Feature: Improve test if Performance Counter category exist

- doc/31-Changelog.md
- lib/icinga/exception/Exit-IcingaPluginNotInstalled.psm1
Improve error handling on plugin execution by informing the user if the plugin is simply not installed or the entire module was not loaded because of errors or missing dependencies
Fixes #250
> Feature: Inform the user if plugins are executed which are not meeting dependency requirements

- lib/webserver/Get-IcingaSSLCertForSocket.psm1
If you tried this
```
Use-Icinga; Get-IcingaSSLCertForSocket -CertFile "C:/my/cert.pfx"
```
the former code expanded like
```
$FileType = Get-Item -Path "C:/my/cert.pfx";
if ("cert.pfx" -eq '.pfx') { ... not reached ... }
```
and thus did not load the certificate file.
Now use `GetExtension` instead of `Get-Item` to make the .pfx check work.
> Fix loading certificate from .pfx file

- doc/31-Changelog.md
- lib/core/icingaagent/misc/Start-IcingaAgentDirectorWizard.psm1
Fixes error while using Icinga Director Self-Service API, in case the host or host API key was deleted inside the Icinga Director and the installation wizard was called with the correct template key, while the old host key was still present inside the Icinga for Windows configuration
Fixes #231
> Fix: Self Service for removed hosts/keys inside Icinga Director

- doc/developerguide/01-New-IcingaCheck.md
- doc/developerguide/02-New-IcingaCheckPackage.md
- lib/core/tools/Convert-Bytes.psm1
- lib/core/tools/Convert-IcingaCheckArgumentToPSObject.psm1
- lib/core/tools/Convert-IcingaPluginValueToString.psm1
- lib/core/tools/ConvertFrom-Percent.psm1
- lib/core/tools/ConvertFrom-TimeSpan.psm1
- lib/core/tools/ConvertTo-BytesNextUnit.psm1
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
- lib/core/tools/Get-IcingaNextUnitIteration.psm1
- lib/help/help/Get-IcingaHelpThresholds.psm1
- lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/ConvertTo-IcingaPluginOutputTranslation.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
- lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
- lib/icinga/plugin/New-IcingaCheckPackage.psm1
- lib/icinga/plugin/New-IcingaCheckResult.psm1
- lib/icinga/plugin/New-IcingaPerformanceDataEntry.psm1
- lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
We re-dessigned the handling on how checks are executed internally, to make configuration, extension and adding future features even more easier.
What is new:
* Allows to specify generic % values for thresholds, in case you added the `BaseValue` argument with the basic value for your input value to compare them as % for each other: `New-IcingaCheck -BaseValue $partition.Size`
* Allows to check for defined thresholds intervalls by the Icinga for Windows daemon, by adding `-ThresholdInterval 15m` for example to your check execution: `Invoke-IcingaCheckCPU -ThresholdInterval 1m -Warning 60%`
* Values of output data which are defined as Bytes, seconds or anything related will now always be properly translated for better readability
* Provided translations for example service states are …
> Feature: Re-Write execution of checks

- lib/core/tools/Convert-IcingaPluginThresholds.psm1
Unhandled units like `c` are causing exceptions, in case they are used as maximum or base value.
> Fix: Unhandled units might cause exception on maximum compare

- lib/icinga/plugin/New-IcingaCheckPackage.psm1
Fixes header summary to no longer count in hidden elements for status counts
> Fix: Header summary should not include hidden packages/elements

- lib/core/tools/ConvertFrom-TimeSpan.psm1
We should round time span values converted to string to transform `22,8934057h` to `22,89h` for example
> Fix: Missing rounding for time span values

- lib/core/tools/Convert-IcingaPluginThresholds.psm1
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Fixes values to be transformed properly to `decimal` to compare them against thresholds provided
> Fix: Numeric converison to comparing thresholds is incorrect

- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
Fixes input value conversion to `decimal` for check input values.
> Fix: Input value from check objects was sometimes not properly converted to decimal

- lib/icinga/plugin/New-IcingaCheckPackage.psm1
Removes the `:` at the end of a package message, in case no additional text input is present on this line
> Fix: Removes colon at the end of the packlage summary

- doc/31-Changelog.md
- lib/core/tools/Convert-IcingaPluginThresholds.psm1
- lib/core/tools/ConvertFrom-TimeSpan.psm1
- lib/core/tools/Test-Numeric.psm1
Fixes `Test-Numeric` to now accept negative numeric values and als fixes errors, causing `.` to be allowed multiple times. `ConvertFrom-TimeSpan` now properly prints on negative values if the time provided is positive or negative and also prints microseconds as `us` in case the value is loer than `1ms`
> Fix: Test-Numeric allows no negative value and TimeSpan conversion ignores negatives and microseconds

- doc/31-Changelog.md
- lib/core/cache/Set-IcingaCacheData.psm1
Fixes unhandled exception on `Set-IcingaCacheData`, as the `-ErrorAction Stop` argument was not set and therefor the function never halted on errors.
> Fix: Unhandled exception on Icinga Cache

- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
- lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
By using an invalid `-ThresholdInterval` argument, PowerShell will terminate itself with `StackOverflowException`, caused by a loop while creating default threshold values.
> Fix: StackOverflowException on invalid ThresholdInterval

- doc/31-Changelog.md
- lib/core/tools/ConvertFrom-TimeSpan.psm1
- lib/core/tools/ConvertTo-Seconds.psm1
Fixes invalid unit conversion, in case first char of a string is matching time metrics
> Fix: Exception on time conversion in case first letter matches time metric

- doc/31-Changelog.md
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/New-IcingaCheckPackage.psm1
Fixes issue on `System.Text.StringBuilder` which fails to initialize properly on some older Windows systems
Fixes #282
> Fix: String builder creation on older windows machines

- doc/31-Changelog.md
- lib/webserver/Read-IcingaRESTMessage.psm1
With the new REST-Api error handler, we detected a NULL exception while parsing REST message content and headers, causing issues and possibly resulting in a memory leak.
> Fix: NULL exception on REST message

- doc/31-Changelog.md
- lib/icinga/plugin/Get-IcingaThresholdCache.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes null exception error which can occur in certain edge cases, caused by testing `New-IcingaCheck` directly without function wrapper.
> Fix: NULL exception on GetBaseThresholdArguments

- doc/10-Knowledge-Base.md
- doc/31-Changelog.md
- doc/knowledgebase/IWKB000009.md
- lib/core/framework/Install-IcingaFrameworkService.psm1
Fixes possible security vulnerability on Icinga for Windows service registration, by not quoting the service path on registration.
You can read more on this on the [Knowledge Base Entry](https://icinga.com/docs/icinga-for-windows/latest/doc/knowledgebase/IWKB000009/) with further details, on how to apply the fix and test if you are affected.
Fixes #298
> Fix: Security vulnerability on Icinga for Windows service register

- doc/31-Changelog.md
- lib/core/tools/Test-IcingaAddTypeExist.psm1
Adds a new Cmdlet to test if functions with `Add-Type` are already present inside the current scope of the shell.
> Feature: Add test function for add type

- doc/31-Changelog.md
- lib/icinga/exception/Exit-IcingaThrowCritical.psm1
- lib/icinga/exception/Exit-IcingaThrowException.psm1
- lib/icinga/plugin/New-IcingaCheckResult.psm1
- lib/icinga/plugin/Set-IcingaInternalPluginException.psm1
- lib/icinga/plugin/Set-IcingaInternalPluginExitCode.psm1
Adds new Cmdlet `Exit-IcingaThrowCritical` to throw critical exit with a custom message, either by force or by using string filtering and adds storing of plugin exit codes internally.
> Feature: Adds critical exception cmdlet and exit code catch

- doc/31-Changelog.md
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Improves error handling in case of exceptions, which will now remove the arguments and content for passwords, in case `String` is tried to be used for `SecureString` arguments.
Fixes #301
> Feature: Removes password on Secure.String exceptions

- doc/31-Changelog.md
- lib/webserver/New-IcingaTCPSocket.psm1
We should ensure the local socket creation always defaults to the loopback interface, while making it configurable on which IP it listens.
> Feature: Adds support to set listen ip, defaults to localhost

- doc/31-Changelog.md
- lib/core/installer/menu/installation/general/Show-IcingaForWindowsInstallerMenuInstallWindows.psm1
- lib/core/installer/menu/manage/agent/Show-IcingaForWindowsMenuManageIcingaAgent.psm1
The reconfigure menu was previously present inside the Icinga Agent sub-menu and is now moved to the main installation menu.
The reason was that in case Agent installation failed, no re-configuration was possible because the entry is locked for the Agent not being present.
> Feature: Relocating reconfigure menu entry

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/tools/ConvertFrom-TimeSpan.psm1
- lib/core/tools/ConvertTo-Seconds.psm1
- lib/core/tools/New-IcingaCheckCommand.psm1
- lib/help/help/Get-IcingaHelpThresholds.psm1
In the past we used different ways to import certain information into Icinga for Windows. With the new version, we can get rid of most of the handling and reduce CPU impact in this matter.
> Deprecated: Remove legacy import feature from files

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
As we move forward with enforcing the Framework Code Cache, we should make it easier for developers to rebuild the cache while testing new features.
For this we now added the `RebuildCache` switch for `icinga` alias and `Invoke-IcingaCommand` which rebuilds the cache before the actual Icinga Shell or Icinga Command is executed.
> Feature: Adds rebuild cache switch to icinga cmd

- doc/31-Changelog.md
- lib/core/tools/Convert-IcingaPluginThresholds.psm1
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
- lib/icinga/plugin/New-IcingaCheckResult.psm1
Adds support to parse arrays to Icinga Check thresholds functions like `WarnOutOfRange` and adds two new functions `WarnDateTime` and `CritDateTime`, for easier comparing of time stamps.
Required for new `Invoke-IcingaCheckScheduledTask` features requested on [Plugin Feature Reqest #208](https://github.com/Icinga/icinga-powershell-plugins/issues/208)
> Feature: Adds array thresholds and date time support

- lib/core/repository/Read-IcingaMSIMetadata.psm1
On Windows 2012 R2, the current implementation for `Read-IcingaMSIMetadata` is not working, as we require to do it on a more complicated way.
> Fix: MSI package reader not working on Windows 2012 R2

- cache/framework_cache.psm1
- doc/31-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/framework/Install-IcingaFrameworkComponent.psm1
- lib/core/framework/Invoke-IcingaNamespaceCmdlets.psm1
- lib/core/framework/Publish-IcingaPluginConfiguration.psm1
- lib/core/repository/Install-IcingaComponent.psm1
- lib/core/tools/New-IcingaCheckCommand.psm1
- lib/icinga/exception/Exit-IcingaPluginNotInstalled.psm1
Fixes import for module files, by using the full path to the module now instead of the name only, as files could be placed inside a folder which is not listed inside the `$ENV:PSModulePath`
> Fix: Module import on non PowerShell folders

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
On certain systems you can run into an exception on the first run of the system, as the module is imported but the cache is written on this import run. Therefor a second import run is required, to import the newly generated files.
> Fix: Possible exception on first import run

- doc/31-Changelog.md
- lib/core/installer/tools/ShowInstallerMenu.psm1
The installer is not overwriting pre-defined values, in case we run in automation mode. This causes default values being used over custom defined values while using the installation file or the intallation command
> Fix: Installer should always overwrite values in automation mode

- doc/31-Changelog.md
- lib/core/framework/Remove-ItemSecure.psm1
The Cmdlet `Remove-ItemSecure` was not using all args and might have crashed on empty values shipped to `-Path`
> Fix: Remove-ItemSecure is not using all args and might fail on empty path

- doc/31-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/installation/AdvancedEntries.psm1
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
- lib/core/installer/menu/installation/icinga/IcingaCAServer.psm1
Fixes Icinga Director Self-Service API which caused exception on some scenarios and stored wrong keys inside configuration.
> Fix: Icinga Director installation on every way for Managment Console

- doc/31-Changelog.md
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Test-IcingaForWindowsService.psm1
- lib/core/repository/Get-IcingaForWindowsServiceData.psm1
Adds a new Cmdlet `Test-IcingaForWindowsService` which will test for security issue IWKB000009 and check if the service is properly configured to run against the .psd1 instead of .psm1 of the icinga-powershell-framework.
> Fatures: Adds Cmdlet to test Icinga for Windows service

- doc/31-Changelog.md
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
Fixes the handling for the Icinga Director Self-Service API, which caused the ticket handling for certificate signing not to work
> Fix: Director Self-Service ticket handling not working

- lib/core/repository/Get-IcingaRepositoryPackage.psm1
The architecture check was missing from the Icinga Repository installation, causing x86 packages being installed on x64 systems and vice versa.
> Fix: Missing architecture check on installation from repository

- doc/31-Changelog.md
- lib/core/icingaagent/misc/Convert-IcingaDirectorSelfServiceArguments.psm1
Fixes an issue on legacy installation wizard, which did not render the zones.conf properly with the correct information shipped for connection data and added missing `-CAEndpoint` assignment, which was wrong previously.
> Fix: Icinga Director Self-Service Zones and CA config

- lib/core/installer/tools/ShowInstallerMenu.psm1
This will highlight the `[a] Hide advanced` and `[h] Hide Help` menu toogle inside the Management Console green, in case active.
> Feature: Highlights advanced/help toogle in mmc

- doc/31-Changelog.md
- lib/core/installer/menu/installation/general/ConfigurationSummary.psm1
Fixes a freeze within Icinga Management Console, in case commands which previously existed were removed/renamed or the user applied an invalid configuration with unknown commands as install file or install command
> Fix: Freeze on IMC in case commands are not found

- doc/repositorymanager/01-Add-Existing-Repositories.md
- doc/repositorymanager/02-Sync-Repositories.md
Fixes the links to publi Icinga repos `stable` and `snapshot`, by always pointing directly to `ifw.repo.json`
> Fix: Links to public Icinga repos

- doc/31-Changelog.md
- lib/core/repository/Get-IcingaRepositoryPackage.psm1
In order to easy manage different snapshot versions for different branches, we now support providing a name as version for **snapshot** packages only,
Example:
```powershell
Add-IcingaRepository -Name 'icinga-powershell-framework/doc/doc_rewrite' -RemotePath 'https://packages.icinga.com/IcingaForWindows/snapshot/icinga-powershell-framework/doc/doc_rewrite/ifw.repo.json';
Install-IcingaComponent -Name 'framework' -Version 'doc/doc_rewrite' -Snapshot -Force;
```
> Feature: Adds support for version names for snapshots

- doc/31-Changelog.md
- icinga-powershell-framework.psm1
Environment variables like `$IcingaEnums` or other similar variables were not exported with Icinga for Windows 1.6.0, causing several other modules and functions to fail.
> Fix: Framework environment variables not working with 1.6.0

- icinga-powershell-framework.psm1
We have to ensure with Icinga for Windows 1.6.0 that we always point to the `.psd1` file instead of the `.psm1` file, especially when working with the `icingapowershellservice`
> Fix: Module file should always point to .psd1 instead of .psm1

- lib/core/tools/Write-IcingaFileSecure.psm1
Fixes newly implemented file writer, by creating files which were not existing prior to writing into them.
> Fix: File writer did not create non-existing files

- lib/core/tools/Write-IcingaFileSecure.psm1
In case we add non-string values into our Icinga file writer, the output may not what we have been expected.
To resolve this, we will add support for these default inputs:
* Hashtable -> JSON
* Array -> Listed output
* PSCustomObject -> JSON
* Everything else -> simple string conversion
> Fix: Icinga file writer fails on input not matching string

- doc/31-Changelog.md
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes an issue on Boolean to empty strong conversion for possible maximum values.
Fixes #300
> Fix: Compare function in Windows 2012 R2

- doc/31-Changelog.md
- lib/icinga/plugin/New-IcingaCheckResult.psm1
- lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
Fixes plain execution of plugin Cmdlets on the PowerShell, which caused an exception of being thrown before, as no check command was assigned.
Fixes #359
> Fix: Plain Plugin Cmdlet execution on shell

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
In case you are using the IMC and the Icinga Director Self-Service API, it can happen that once entered the Self-Service API key, the shell will only look like this:
```
Input (Default 0 and c ):
```
Without any other form content.
This occured, in case inside the Self-Service API config the entry `Installation Source` was set to `- no automatic installation -`.
This fix resolves the issue and renders the form including the settings correctly.
> Fix: IMC fails on Icinga Director Self-Service no Agent installation set

- doc/100-General/10-Changelog.md
- lib/core/repository/Read-IcingaRepositoryFile.psm1
- lib/core/repository/Search-IcingaRepository.psm1
- lib/web/Invoke-IcingaWebRequest.psm1
The installation from file share locations will fail, in case no `LocalPath` is assigned to the repository configuration and is also failing by invalid escaping of the path.
This is now fixed as the `RemotePath` is the only one being required and in addition downloads from file shares of component packages is now working as intended.
> Fix: Repository component install from file share

- doc/100-General/10-Changelog.md
- lib/core/jea/Test-IcingaJEAServiceRunning.psm1
In case no JEA pid is present, we should not lookup any processes and simply return `False` instead.
> Fix: Unneeded continue on no JEA pid present

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
In case the Icinga Director host is registered in the IMC over the Self-Service API, the menu is defaulting to the message "Do not register host" instead of displaying the correct configuration.
This is only a displaying issue and has no technical impact, but we still need to fix that.
> Fix: Icinga Director state not being saved on overview

- doc/100-General/10-Changelog.md
- lib/core/repository/Read-IcingaRepositoryFile.psm1
Fixes lookup for local ifw.repo.json, in case the path was specified with `ifw.repo.json` included, like `C:\icinga\stable\ifw.repo.json`
> Fix: Repository lookup on local path for ifw.repo.json

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/general/ConfigurationSummary.psm1
Fixes misleading title for IMC summary header, which implies the installation instantly starts on continue, instead of notifying properly about the installation being started on the next step including the export of the answer file and install command.
> Fix: IMC summary header has misleading title

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/general/ConfigurationSummary.psm1
Fixes wrong indention on Icinga parent host address at IMC configuration summary.
> Fix: Wrong IMC indention on host address summary

- doc/100-General/10-Changelog.md
- lib/config/Get-IcingaPowerShellConfig.psm1
- lib/config/Test-IcingaPowerShellConfigItem.psm1
- lib/core/repository/Add-IcingaRepository.psm1
- lib/core/repository/Disable-IcingaRepository.psm1
- lib/core/repository/Enable-IcingaRepository.psm1
- lib/core/repository/New-IcingaRepository.psm1
- lib/core/repository/Pop-IcingaRepository.psm1
- lib/core/repository/Push-IcingaRepository.psm1
- lib/core/repository/Read-IcingaRepositoryFile.psm1
- lib/core/repository/Remove-IcingaRepository.psm1
- lib/core/repository/Sync-IcingaRepository.psm1
- lib/core/repository/Update-IcingaRepository.psm1
Fixes repository names with dots (`.`) by replacing them with `-`, as otherwise the config parser will fail finding the config object
> Fix: Repository names with dots fail to load

- doc/100-General/10-Changelog.md
- lib/core/framework/Uninstall-IcingaForWindows.psm1
Fixes an exception on the last message output while running `Uninstall-IcingaForWindows`, as the used function is no longer available due to Framework uninstallation.
We now replaced the last messages with proper `Write-Host` output
> Fix: Exception on last uninstall message print

- doc/100-General/10-Changelog.md
- lib/core/installer/Install-Icinga.psm1
- lib/core/installer/tools/CustomConfig.psm1
Fixes error handling for IMC on automated installation with installation command or answer file, which will not abort the installation in case invalid JSON is provided or commands are used inside the command, not valid or exist on the system.
The system will write an error message and abort the installation in case of initial errors now.
> Fix: IMC error handling on invalid JSON for install command/file

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
Starting with Icinga 2.13.0, the Agent will write to the Windows EventLog by default. Our `Read-IcingaAgentLogFile` Cmdlet will now support both and read from the EventLog if the feature is enabled and 2.13.0 or later is being installed
> Feature: Adds support to read EventLog for logs

- doc/100-General/10-Changelog.md
- doc/110-Installation/05-Background-Daemons.md
- doc/110-Installation/06-Collect-Metrics-over-Time.md
- doc/900-Developer-Guide/00-General.md
- doc/900-Developer-Guide/01-New-IcingaCheck.md
- doc/900-Developer-Guide/10-Custom-Daemons.md
- doc/900-Developer-Guide/11-Custom-Plugins.md
- doc/900-Developer-Guide/12-Custom-API-Endpoints.md
- lib/core/dev/New-IcingaForWindowsComponent.psm1
- lib/core/dev/Open-IcingaForWindowsComponentInEditor.psm1
- lib/core/dev/Publish-IcingaForWindowsComponent.psm1
- lib/core/dev/Test-IcingaForWindowsComponent.psm1
- lib/core/dev/Write-IcingaForWindowsComponentManifest.psm1
- lib/core/framework/Publish-IcingaPluginConfiguration.psm1
- lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
- templates/Manifest.psd1.template
- templates/PSScriptAnalyzerSettings.psd1.template
Adds additional Cmdlets to get working on new Icinga for Windows components and publishing of  modules including validation alot easier.
`New-IcingaForWindowsComponent`: Creates an entire new module structure depending on input values, to get a base skeleton for further development ready
`Publish-IcingaForWindowsComponent`: Properly adds documentation, possible plugin configuration and dependencies of files to the manifest file, ensuring the integrity of the module
`Test-IcingaForWindowsComponent`: Allows to test your module and checks for code styling issues and errors as well as testing the module itself, if it can be imported, printing errors in case of problems
`Open-IcingaForWindowsComponentInEditor`: Allows to open a certain Icinga for Windows component in an editor to get started a …
> Feature: Adds developer tools for easier start and management

- doc/100-General/10-Changelog.md
- lib/core/dev/Write-IcingaForWindowsComponentManifest.psm1
Fixes String.Builder object output, while creating new components by using `New-IcingaForWindowsComponent`
> Fix: Removes String.Builder output while creating new components

- doc/100-General/10-Changelog.md
- lib/core/repository/Read-IcingaRepositoryFile.psm1
- lib/core/repository/Sync-IcingaRepository.psm1
Fixes the repository manager by now using Icinga WebRequests instead of Windows WebRequests, allowing the usage of the internal proxy feature.
> Fix: Repository Manager is not using Icinga Web-Requests

- doc/100-General/10-Changelog.md
- lib/core/repository/Get-IcingaRepositoryHash.psm1
Fixes repository file hash generator, which now only includes .zip and .msi files, which otherwise turned into invalid hashes because of the repository index file always changing based on the assigned hash, resulting in a different repository hash
Fixes #399
> Fix: Repo hash generator causes file hashes to never compare

- doc/100-General/10-Changelog.md
- lib/core/framework/Read-IcingaWindowsEventLog.psm1
With Icinga for Windows v1.7.0 we introdocued a way to read EventLog entries as stream directly into the CLI.
If used for a long time, the memory consumption of this active shell will increase over time, as the Garbage Collector does not kick in.
This will fix the issue by forcing the GC to be called after each loop cycle.
> Fix: Memory leak on EventLog reader

- doc/100-General/10-Changelog.md
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
Fixes missing address attribute for REST-Api daemon, making it unable to change the listening address
Fixes #402
> Fix: REST-Api address argument not being used

- doc/100-General/10-Changelog.md
- doc/100-General/20-Eventlog.md
- lib/core/framework/Invoke-IcingaNamespaceCmdlets.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
Removes not required import of PowerShell modules for `Invoke-IcingaNamespaceCmdlets`, as by the time we fetch the content the specified module must be loaded already.
In addition adds proper error output in case something goes wrong. Errors are written directly into the EventLog.
> Fix: Removes unnecessary module import

- doc/100-General/10-Changelog.md
- lib/core/framework/Get-IcingaPrivateEnvironmentVariable.psm1
- lib/core/framework/New-IcingaCheckSchedulerEnvironment.psm1
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- lib/core/framework/Set-IcingaPrivateEnvironmentVariable.psm1
- lib/core/tools/Test-IcingaAddTypeExist.psm1
With recent versions we added a feature to test if Add-Type functions are added to the current PowerShell session, ensuring that the same type is not re-added which caused errors on the error stack.
While the code works perfectly fine, it takes a long time for execution which causes the plugin `Invoke-IcingaCheckDiskHealth` for example, to take way longer than usual.
This PR prepares the future `Private` and `Public` section of the Icinga for Windows environment variables and adds an internal, quick test if a Add-Type function is already added to the current session, once being tested with the old behaviour.
This reduces the disk health plugin execution time after the first run from around 10 seconds to 2 seconds.
Fixes #388
> Fix: Performance for Add-Type testing

- doc/100-General/10-Changelog.md
- lib/core/framework/Read-IcingaWindowsEventLog.psm1
- lib/core/tools/Optimize-IcingaForWindowsMemory.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
- lib/daemons/ServiceCheckDaemon/Add-IcingaServiceCheckTask.psm1
In some scenarios, Icinga for Windows can contain a memory leak, caused by a bug of the Garbage Collector in older PowerShell versions.
We resolve this by enforcing a more aggressive approach on memory cleanup and by collecting all objects being used.
Fixes #379
> Fix: Icinga for Windows memory leak

- doc/100-General/10-Changelog.md
- lib/apis/Get-IcingaDirectorSelfServiceTicket.psm1
Fixes a crash while generating the cache file, because of wrong variable usage introduced with #411.
> Fix: Crash on wrong variable usage

- doc/100-General/10-Changelog.md
- lib/core/jea/Install-IcingaJeaProfile.psm1
- lib/core/windows/Install-IcingaSecurity.psm1
- lib/core/windows/New-IcingaWindowsUser.psm1
JEA profile installation can fail and cause the Icinga Agent to become defective, in case a username is used being longer than 20 digits.
Fixes #412
> Fix: Username has no length cap for JEA installation

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/misc/Compare-IcingaVersions.psm1
- lib/core/icingaagent/misc/Split-IcingaVersion.psm1
Fixes the output value from `Split-IcingaVersion` by returning the object `major`  in addition to the wrong value `mayor`.
We will keep both outputs present for the moment, allowing developers to update their code.
Fixes #291
> Fix: Version splitting returns "mayor" instead of "major"

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/getters/Get-IcingaAgentMSIPackage.psm1
- lib/core/repository/Sync-IcingaRepository.psm1
- lib/core/repository/Test-IcingaValidJSON.psm1
By using the `Sync-IcingaRepository` function, it might happen that in case the parent site is returning a file listing instead of an error page, the downloaded **repository** file is only the list of the files and not the proper JSON repo file.
Instead we now check the result properly and fallback by adding `ifw.repo.json` as it was intended before.
Fixes #409
> Fix: Sync-IcingaRepository can cause invalid JSON primitive

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/installation/AdvancedEntries.psm1
- lib/core/installer/menu/installation/icinga/ForceCertificateGeneration.psm1
Adds support to re\-create the Icinga Agent certificates, even when they are already present on the system. This will resolve the manual requirement to delete the folder or certificates, in case the Icinga CA changes for example
Fixes \#417
> Feature: Allow Force-Creation of certificates for Agent over IMC

- doc/100-General/10-Changelog.md
- lib/core/windows/Get-IcingaWindowsUserConfig.psm1
- lib/core/windows/New-IcingaWindowsUser.psm1
- lib/core/windows/Remove-IcingaWindowsUser.psm1
- lib/core/windows/Test-IcingaManagedUser.psm1
- lib/core/windows/Update-IcingaServiceUser.psm1
Fixes the lookup time if a user is managed by Icinga for Windows or not in large Active Directory environments, by using `Get-LocalUser` instead.
This Cmdlet is available starting with PowerShell 5.0 and later and only required in general for running Icinga for Windows in JEA context. As JEA is only supported starting with PowerShell 5.0 or later, this will not cause any problems.
In case the command is executed on an older system without the `Get-LocalUser` Cmdlet available, Icinga for Windows will handle all users tested with the new implementation as `not` managed by Icinga for Windows.
Fixes #394
> Fix: Icinga Managed User lookup time

- doc/100-General/10-Changelog.md
- lib/core/framework/Disable-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Enable-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Get-IcingaFrameworkApiChecks.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/core/installer/menu/manage/framework/FrameworkExperimental.psm1
- lib/core/installer/menu/manage/framework/ManageFramework.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes experimental state of `API Check` feature by removing that term and removing the requirement to install `icinga-powershell-restapi` and `icinga-powershell-apichecks`
Fixes #421
> Fix: Removes experimental for API Checks and module requirements

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Fixes Icinga for Windows exception while running `icinga` commands or the Icinga Mangement Console inside an `PowerShell ISE` session, which behaves differently.
Instead, we now load Icinga for Windows and inform the user about limitations properly.
Fixes #273
> Fix: Exception and freezes inside PowerShell ISE session

- doc/100-General/01-Upgrading.md
- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/framework/Read-IcingaForWindowsLog.psm1
- lib/core/framework/Set-IcingaForWindowsMigration.psm1
- lib/core/framework/Test-IcingaForWindowsMigration.psm1
- lib/core/framework/Uninstall-IcingaForWindows.psm1
- lib/core/logging/Icinga_EventLog_DebugEnums.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
- lib/core/logging/Register-IcingaEventLog.psm1
- lib/core/logging/Register-IcingaForWindowsEventLogEnvironment.psm1
- lib/core/logging/Unregister-IcingaEventLog.psm1
- lib/core/logging/Write-IcingaDebugMessage.psm1
- lib/core/logging/Write-IcingaErrorMessage.psm1
- lib/core/logging/Write-IcingaEventMessage.psm1
- lib/core/repository/Install-IcingaComponent.psm1
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
We will move the Icinga for Windows EventLog away from the current `Application` log and move it into a custom `Icinga for Windows` log, to ensure the `Application` log is not spammed with Icinga for Windows events.
Fixes #427
> Feature: Moves EventLog out of Application log for IfW

- doc/100-General/10-Changelog.md
- lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Fixes a lookup error for existing plugin documentation files, which caused files not being generated properly in case a similar name was already present on the system.
> Fix: Plugin Doc generator file lookup

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
Ensures we add an upgrade notification if we are running the Icinga for Windows Service binary older than v1.2.0, which will not work with Icinga for Windows v1.8.0 or later.
> Feature: Adds upgrade notification to service binary

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Fixes an exception while loading the Framework, caused by a race condition for missing environment variables which are accessed by some plugins before the Framework is loaded properly.
> Fix: Exception on loading by missing environment

- cache/framework_cache.psm1
- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
In some cases it can happen, that Icinga for Windows throws an exception while using \`Use\-Icinga\`. This happens because of an internal handling for rebuilding the cache, which tried to re\-import the modules.
This code seems no longer to be required and causes only problems while trying to use \`Use\-Icinga\` while inside the same shell, that Icinga for Windows is being installed the first time in.
As this seems no longer to be required, we will remove this code.
Fixes \#380
> Fix: Exception on Use-Icinga

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/installer/Repair-IcingaService.psm1
In some cases it can happen, that during an upgrade of the Icinga Agent, the service fails because on how the .msi installer works.
This adds a new Cmdlet `Repair-IcingaService`, which resolves the problem and repairs the service.
> Feature: Adds command to repair Icinga Agent service

- doc/100-General/10-Changelog.md
- lib/core/tools/ConvertTo-IcingaSecureSortedArray.psm1
Adds a new function, allowing to sort arrays with objects inside for specific members wihtout having to use ScriptBlocks on external modules.
This allows a secure usage even in JEA context and external modules are not blocked by calling `ScriptBlocks`
> Feature: Adds support to sort arrays without ScriptBlocks

- doc/100-General/10-Changelog.md
- lib/core/repository/Install-IcingaComponent.psm1
Adds improved exception handling for using `Install-IcingaComponent` while importing of modules failed, because of missing dependencies for example.
> Fix: Error handling for failed module import

- doc/100-General/10-Changelog.md
- doc/110-Installation/05-Background-Daemons.md
- doc/110-Installation/06-Collect-Metrics-over-Time.md
- lib/core/installer/tools/Write-IcingaManagementConsoleCommand.psm1
- lib/core/repository/Show-Icinga.psm1
- lib/core/tools/ConvertTo-IcingaCommandArgumentString.psm1
- lib/daemon/Show-IcingaRegisteredBackgroundDaemons.psm1
- lib/daemons/ServiceCheckDaemon/tools/Register-IcingaServiceCheck.psm1
- lib/daemons/ServiceCheckDaemon/tools/Show-IcingaRegisteredServiceChecks.psm1
- lib/daemons/ServiceCheckDaemon/tools/Unregister-IcingaServiceCheck.psm1
Improves show command `Show-IcingaRegisteredServiceChecks` to use new layout for displaying information and adds new command `Show-IcingaRegisteredBackgroundDaemons`, following the same layout and possiblity.
In addition extends `Show-Icinga` by both commands and adds debug and api forwarder features to environment list.
> Feature: Improve show commands and extend Show-Icinga

- doc/100-General/10-Changelog.md
- lib/core/jea/Get-IcingaJEAConfiguration.psm1
- lib/icinga/plugin/Write-IcingaPluginResult.psm1
Fixes the PowerShell not being able to enter the JEA context, if only the Icinga PowerShell Framework is installed and no other component like plugins being present.
Fixes in addition the output for the JEA PowerShell, in case a check command cannot be executed. Previously the pipe `|` for performance data was always added, which is now gone.
> Fix: JEA context cannot be created and command not found output

- .gitignore
- doc/100-General/10-Changelog.md
- lib/core/dev/New-IcingaForWindowsComponent.psm1
- lib/core/jea/Get-IcingaCommandDependency.psm1
- lib/core/jea/Get-IcingaJEAConfiguration.psm1
- lib/core/jea/Read-IcingaPowerShellModuleFile.psm1
- lib/core/jea/Set-IcingaForWindowsServiceJEAProfile.psm1
- lib/core/thread/New-IcingaThreadInstance.psm1
- lib/core/thread/New-IcingaThreadPool.psm1
- lib/core/thread/Set-IcingaEnvironmentJEA.psm1
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
The current implementation of the Icinga for Windows background daemon was not working entirely by using JEa profiles.
We fixed the behavior by resolving a problem within our JEA profile catalog builder as well as other factors causing issues. All background daemons will now work properly inside the JEA context.
> Fix: Background daemon not working in JEA context

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
- lib/icinga/plugin/Write-IcingaExecutePluginException.psm1
Adds support for the remote execution plugin [check_by_icingaforwindows](https://github.com/LordHepipud/check_by_icingaforwindows), allowing to check from a Linux or Windows remote host by using WinRM to a target Windows machine.
Fully supports JEA profiles, but requires powershell installed on the Linux machine.
> Feature: Adds support for check_by_icingaforwindows.ps1

- doc/100-General/10-Changelog.md
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
While running the Icinga for Windows service in JEA context, it can happen that the corresponding WinRM service is restarted or terminated. The service daemon will keep an eye on that and restart the JEA session up to 5 times, before terminating the service and printing an error.
This fix will not add a grace period, which will reset the failure counter in case the service was running for more than 3 minutes. Which is more then enough runtime to not asume a faulty service behavior.
> Fix: JEA service error count not resetting itself

- doc/100-General/10-Changelog.md
- lib/core/windows/Install-IcingaSecurity.psm1
We have to ensure that `Install-IcingaSecurity` is only allowed to be excuted from an administrative shell to not cause any errors.
> Fix: Install-IcingaSecurity should only run in administrative shell

- doc/100-General/10-Changelog.md
- lib/core/repository/Get-IcingaInstallation.psm1
Fixes `Update-Icinga` which now supports to update from a snapshot branch and to downgrade properly from snapshot to stable to the latest release packages again.
**NOTE:** It is still **not** entirely supported to downgrade from snapshot to stable, as possible migrations for later versions will **not** be rolled back.
> Fix: Update-Icinga not working between snapshot/stable

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes Icinga Agent installation over IMC and Director Self-Service, in case the Self-Service is configured to not install the Icinga Agent or the user manually set `Do not install Icinga Agent` inside the IMC, which results in most configurations not being applied to the Agent, in case it is already installed
Fixes #460
> Fix: Icinga Agent not configured properly if not installed over IMC and installation disabled there

- doc/100-General/10-Changelog.md
- lib/core/repository/Add-IcingaRepository.psm1
Fixes `Add-IcingaRepository` which now only overrides the `RemotePath` by using `-Force` instead of removing and adding the repository again, causing problems with installation orders over IMC for example
Fixes #461
> Fix: Add-IcingaRepository removes and adds repository with -Force

- doc/100-General/10-Changelog.md
- lib/core/framework/Uninstall-IcingaForWindows.psm1
Fixes the Icinga for Windows uninstaller which did not remove the service binary.
> Fix: Icinga for Windows uninstaller not removing service binary

- .gitignore
- doc/100-General/10-Changelog.md
- lib/core/jea/Get-IcingaJEAConfiguration.psm1
- lib/core/tools/Add-IcingaAddTypeLib.psm1
- lib/core/tools/Clear-IcingaAddTypeLib.psm1
Icinga for Windows is using `Add-Type` in some small cases, to properly fetch UNC Path values for plugins or disk attribute information.
While in most cases this works without problems, sometimes the on-the-fly compilation fails because of out-of-memory exceptions or different errors.
This fix will now compile the DLL required inside the `cache/dll` folder if not present and load the compiled DLL's if required and available.
> Fix: Errors while dynamically compiling Add-Type

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/AdvancedEntries.psm1
- lib/core/installer/menu/installation/certificate/EnterIcingaCAFile.psm1
- lib/core/installer/menu/installation/certificate/SelectCertificate.psm1
- lib/core/installer/menu/installation/icinga/SelectConnection.psm1
While using the IMC with the connection option "Connecting from parent system", the wizard is not asking for the location of the ca.crt, which is required in order to complete the Icinga Agent process and ensure the API feature can be enabled afterwards.
Before, the user had to manually configure this step, which required knowledge on how this process works for Icinga.
> Fix: Option "Connecting from parent system" is not asking for ca.crt

- doc/100-General/10-Changelog.md
- lib/core/framework/Get-IcingaPowerShellModuleArchive.psm1
- lib/core/framework/Remove-ItemSecure.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes possible exceptions while trying to remove downloaded repository temp files which might still contain a file lock from virusscanners or other tasks
> Fix: Exceptions while removing temp files from repository download

- doc/100-General/10-Changelog.md
- lib/core/framework/Install-IcingaFrameworkComponent.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Restart-IcingaService.psm1
- lib/core/framework/Start-IcingaService.psm1
- lib/core/framework/Stop-IcingaService.psm1
- lib/core/icingaagent/installer/Install-IcingaAgent.psm1
- lib/core/icingaagent/installer/Uninstall-IcingaAgent.psm1
- lib/core/installer/menu/manage/settings/services/ManageServices.psm1
- lib/core/jea/Test-IcingaJEAServiceRunning.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes service locking during Icinga Agent upgrade and ensures errors on service management are caught and printed with internal error handling
> Fix: Service locking and error handling

- lib/core/framework/Install-IcingaFrameworkComponent.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Restart-IcingaService.psm1
- lib/core/framework/Start-IcingaService.psm1
- lib/core/framework/Stop-IcingaService.psm1
Fixes unhandled Icinga output introduced with #480
> Fixes unhandled Icinga output

- doc/100-General/10-Changelog.md
- lib/core/repository/Uninstall-IcingaComponent.psm1
Fixes the command `Uninstall-IcingaComponent` for the `service` component which is not working.
> Fix: Uninstaller for service component not working

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/getters/Get-IcingaAgentHostCertificate.psm1
- lib/core/icingaagent/getters/Get-IcingaHostname.psm1
- lib/webserver/Get-IcingaSSLCertForSocket.psm1
Fixes REST-Api SSL certificate lookup from the Icinga Agent, in case a custom hostname was used or in certain domain environments were domain is not matching DNS domain
Fixes #483
> Fix: REST-Api SSL certificate lookup on custom hostname or domain/dns domain mismatch

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
Improves REST-Api default timeout for internal plugin execution calls from 30s to 120s
> Fix: Improves REST-Api default timeout

- doc/100-General/10-Changelog.md
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
- lib/core/thread/New-IcingaThreadInstance.psm1
- lib/core/thread/Remove-IcingaThread.psm1
- lib/core/thread/Set-IcingaEnvironmentThreadName.psm1
- lib/core/thread/Stop-IcingaThread.psm1
- lib/daemon/Add-IcingaForWindowsDaemon.psm1
- lib/daemon/Set-IcingaForWindowsThreadAlive.psm1
- lib/daemon/Suspend-IcingaForWindowsFrozenThreads.psm1
- lib/daemons/RestAPI/threads/Get-IcingaNextRESTApiThreadId.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
- lib/daemons/RestAPI/threads/Start-IcingaForWindowsRESTThread.psm1
Adds feature to check for frozen threads on REST-Api, ensuring that non-responding threads are killed after 5 minutes without progress and restartet.
Also improves queing of REST-Api tasks into threads, which now prioritizes to check for inactive threads first to enque new calls and falls back to old behaviour, in case all threads are busy.
> Feature: Add thread queuing optimisation and frozen thread detection

- doc/100-General/10-Changelog.md
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/daemon/Start-IcingaWindowsRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
The former implementation had 5 threads permanently spinning fast (10ms sleep) while waiting for a REST connection to process. This causes higher load in general and it breaks systems where [Turn on PowerShell Script Block Logging](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_logging_windows?view=powershell-7.2#using-group-policy) policy is enabled, because then each PS statement including `Start-Sleep` is logged - resulting in 500 event log entries per second. It's a suggested setting in some hardening guidelines.
We can easily replace the Queue with a [BlockingCollection](https://docs.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1?view=net-6.0) backed by a …
> Use a BlockingCollection to avoid busy loop in REST API threads

- doc/100-General/10-Changelog.md
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- lib/core/tools/Optimize-IcingaForWindowsMemory.psm1
- lib/daemon/Add-IcingaForWindowsDaemon.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
- lib/daemons/ServiceCheckDaemon/daemon/Add-IcingaServiceCheckDaemon.psm1
- lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
Fixes GC collection with `Optimize-IcingaForWindowsMemory` for every incoming REST connection call
Fixes #491
> Fix: GC collection on every REST call

- doc/100-General/10-Changelog.md
- doc/900-Developer-Guide/00-General.md
- lib/core/dev/Get-IcingaForWindowsComponentPublicFunctions.psm1
- lib/core/dev/New-IcingaForWindowsComponent.psm1
- lib/core/dev/Publish-IcingaForWindowsComponent.psm1
- lib/core/dev/Test-IcingaForWindowsComponentPublicFunctions.psm1
- lib/core/dev/Update-IcingaForWindowsManifestArray.psm1
- lib/core/dev/Write-IcingaForWindowsComponentCompilationFile.psm1
- lib/core/dev/Write-IcingaForWindowsComponentManifest.psm1
- lib/core/jea/Get-IcingaJEAConfiguration.psm1
- lib/core/jea/Read-IcingaPowerShellModuleFile.psm1
- templates/Manifest.psd1.template
- templates/compilation.psm1.template
Improves writing and publishing of modules, by ensuring that only certain functions are exported and modules have an own compilation file for loading.
This reduces load times, execution time and in addition allows modules to be isolated from each other, making it impossible to hijack certain code for not exported functions.
> Features: Adds module isolation support

- lib/core/dev/New-IcingaForWindowsComponent.psm1
- templates/Manifest.psd1.template
With the new module isolation, we no longer require the `RootModule` entry for manifest files.
> Fix: Removes RootModule from Manifest file

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Fixes missing loading of Icinga for Windows modules, which is required to ensure an Icinga for Windows environment is providing all commands and variables to a session, allowing other modules to access these information.
> Fix: Missing loading for Icinga for Windows modules

- doc/100-General/10-Changelog.md
- lib/core/dev/New-IcingaForWindowsComponent.psm1
Adds missing `Import-IcingaPowerShellComponent` function while creating new components by using the developer tools
> Fix: Missing component import func on dev tools

- doc/100-General/10-Changelog.md
- lib/core/framework/Install-IcingaFrameworkComponent.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Restart-IcingaService.psm1
- lib/core/framework/Start-IcingaService.psm1
- lib/core/framework/Stop-IcingaService.psm1
- lib/core/icingaagent/installer/Install-IcingaAgent.psm1
- lib/core/icingaagent/installer/Uninstall-IcingaAgent.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes errors on encapsulated PowerShell calls for missing Cmdlets `Write-IcingaConsoleError` and `Optimize-IcingaForWindowsMemory`, while trying to restart services or appling configurations which require a new PowerShell session.
Fixes #523
> Fix: Exceptions on encapsulated PowerShell calls for missing Cmdlets

- doc/110-Installation/01-Getting-Started.md
the actual file name for the json file is missing in the example, which is misleading.
> Fix missing file name in URL

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/framework/Uninstall-IcingaForWindows.psm1
- lib/core/installer/Install-Icinga.psm1
- lib/core/repository/Uninstall-IcingaComponent.psm1
Improves internal component uninstaller and Icinga for Windows uninstaller to ensure folders are not locked during uninstallation with the current PowerShell sessions
Fixes #524
> Fix: Uninstaller removal errors by improving location handling

- doc/100-General/10-Changelog.md
- lib/daemon/Get-IcingaBackgroundDaemons.psm1
Fixes `You cannot call a method on va null-valued expression` during installation or while enabling JEA, in case no background daemons have been configured.
Fixes #476
Fixes #487
> Fix: Null-value exception on missing background daemons

- icinga-powershell-framework.psm1
Fixes the `icinga` command which always resets the Framework cache, caused by newly introduced `Developer Mode`
> Fix: icinga command always resetting cache

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Fixes an issue with current implementation, as string values containing whitespaces or `$` are rendered wrong by default, if not set in single quotes `''`
Example:
Using `My Service`
will output
`My`
`Service`
This issue is already fixed for arrays, but plain string values on arguments require this workaround.
As Icinga 2 will always set arguments if a DSL is specified, regardless if a value is present or not, we have to use a `set_if` expression for this, but can't as the Icinga Director baskets currently ignore `set_if_format` which requires to be an expression instead of a string.
https://github.com/Icinga/icingaweb2-module-director/issues/2291
This PR is pending as long as the Director issue is not fixed and released within a release.
> Fix: Adds DSL parser to string arguments to fix whitespace and $ escaping

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/core/icingaagent/readers/Read-IcingaAgentDebugLogFile.psm1
- lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
- lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
- lib/core/tools/ConvertTo-IcingaUTF8Value.psm1
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Fixes Icinga for Windows plugin execution, by converting all parsed arguments and values from Icinga 2 from the `Default` of the PowerShell to `UTF8`.
This resolves issues during plugin execution on which arguments like `-Path`, `-TaskName` or anything else contained characters like `äöüß`.
In addition, we created an internal `StringBuilder` to resolve current issues on which unescaped strings within the Icinga configuration like `Icinga for Windows` instead of `'Icinga for Windows'`, are interpreted as `Icinga` instead of `Icinga for Windows` because of the whitespaces.
The new argument parser will test for this and create a proper string output value.
> Fix: Encoding problems with special chars or German umlauts

- doc/100-General/10-Changelog.md
- lib/core/repository/Update-IcingaRepository.psm1
Fixes `RemoteSource` being cleared within repository `.json` files during `Update-IcingaRepository` tasks
Fixes #545
> Fix: RemoteSouce being cleared during Update-IcingaRepository

- cache/framework_cache.psm1
- doc/100-General/01-Upgrading.md
- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Fixes file encoding for Icinga for Windows v1.10.0 to ensure the cache is always properly created with the correct encoding
> Fix: Cache file encoding read/write

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
Fixes certificate generation and host registration, in case a custom hostname was set during usage of `Install-Icinga` automation
Fixes #505
> Fix: Automated Icinga Director installation for custom hostname

- doc/100-General/10-Changelog.md
- lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
- lib/icinga/plugin/Exit-IcingaExecutePlugin.psm1
Fixes negative thresholds being interpreted wrongly as argument instead of an value for an argument
Fixes #528
> Fix: Negative thresholds interpreted as argument

- doc/100-General/10-Changelog.md
Fixes the certificate folder not present during first installation, preventing permissions properly set from the start which might cause issues once required
> Fix: Certificate folder not present on first installation

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/framework/Uninstall-IcingaForWindows.psm1
- lib/core/installer/Install-Icinga.psm1
- lib/core/installer/tools/SetCloseIMC.psm1
- lib/core/installer/tools/SetUpdatingIMC.psm1
- lib/core/installer/tools/TestUpdatingIMC.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Improves the Icinga Management Console (IMC) during uninstallation of Icinga for Windows entirely and during updates of the Icinga PowerShell Framework.
The IMC will during uninstallation now properly close and not being stuck inside a loop or errors messages, while after updates the current IMC will close and restart itself with the new configuration.
> Feature: Improves IMC update and uninstall handling for Framework

- doc/100-General/10-Changelog.md
- lib/icinga/plugin/Write-IcingaPluginResult.psm1
Fixes corrupt Performance Data, in case plugins were executed inside a JEA context without the REST-Api.
> Fix: PerfData writer in JEA context without REST-Api

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
- lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Fixes checks like MSSQL using arguments of type `SecureString` not being usable with the Icinga for Windows REST-Api
Fixes #563
> Fix: SecureString arguments not working with REST-Api

- doc/100-General/10-Changelog.md
- lib/core/cache/Copy-IcingaCacheTempFile.psm1
- lib/core/cache/Get-IcingaCacheData.psm1
- lib/core/cache/Set-IcingaCacheData.psm1
- lib/core/cache/Test-IcingaCacheDataTempFile.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
Ensures that new cache files will always be written inside a `.tmp` file at the same location and tested for validation before applied to the regular file via copy.
This should prevent files becoming corrupt in the future during write operations.
> Feature: Improve cache file writer with more robust handling

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/tests/Test-IcingaAgent.psm1
Fixes useless testing and printing of error messages, in case the Icinga Agent is not installed during installation and Icinga for Windows printing plenty of errors, because the ACL checks cannot be completed.
> Fix: Useless testing for directories if agent is not installed

- lib/core/icingaagent/setters/Set-IcingaUserPermissions.psm1
Fixes missing certificate folder permission update on every change for the Icinga Agent user, as the folder wasn't present by default before, which changed with v1.10.0
> Fix: Missing permission update for certificate directory

- doc/100-General/10-Changelog.md
- lib/core/windows/Uninstall-IcingaServiceUser.psm1
Fixes misleading SID error during uninstallation of Icinga for Windows or the Agent component
> Fix: Misleading SID error during uninstallation

- doc/100-General/10-Changelog.md
- lib/core/framework/Read-IcingaForWindowsLog.psm1
- lib/core/framework/Read-IcingaWindowsEventLog.psm1
- lib/core/icingaagent/readers/Read-IcingaAgentLogFile.psm1
Adds `-Include` and `-Exclude` filter for EventLog CLI parser, to only contain certain messages or exclude them from the output.
> Feature: Adds filtering options for EventLog parser

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
We have decided to now officially deprecate the previous installation method `Start-IcingaAgentInstallWizard`. It hasn't been updated or promoted in a long time and all new features have been moved to the [Icinga Management Console](https://icinga.com/docs/icinga-for-windows/latest/doc/110-Installation/02-Icinga-Management-Console/). Please update your installation method to the new solution. The old method will be removed in a future release.
> Deprecated: Start-IcingaAgentInstallWizard installation method

- lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
Caused by newly introduced `Get-Help` check to fetch argument types
> Fix: StackTrace in plugin output, when plugin is not installed

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
Fixes background service registration caused by migration task for v1.10.0 being executed even when no services were defined before
Fixes #582
> Fix: Background service registration

- doc/100-General/10-Changelog.md
- lib/core/tools/Convert-Bytes.psm1
- lib/core/tools/Convert-IcingaPluginThresholds.psm1
- lib/core/tools/Convert-IcingaPluginValueToString.psm1
- lib/core/tools/Get-IcingaNetworkInterfaceUnits.psm1
Fixes threshold values causing an error because of too aggressive regex expression
Fixes #588
> Fix: Wrong regex for threshold detection

- doc/100-General/10-Changelog.md
- lib/core/tools/ConvertTo-IcingaPowerShellArguments.psm1
Fixes plugin argument parser to proceed with real argument names and possible provided aliases
Fixes #599
> Fix: Command aliases not evaluated on plugin run

- doc/100-General/10-Changelog.md
- lib/core/dev/Write-IcingaForWindowsComponentCompilationFile.psm1
- lib/core/framework/Uninstall-IcingaForWindows.psm1
- lib/core/repository/Uninstall-IcingaComponent.psm1
- lib/core/tools/Set-IcingaPSLocation.psm1
Fixes installation and uninstallation commands changing PowerShell location even when not necessary
Fixes #578
> Fix: Unintended PS path change

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaServices.psm1
Fixes service filter to handle exclude with wildcards instead of requiring the full service name (*not* applying to the display name)
#Fixes 603
> Fix: Service exclude filter for wildcards

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
We should nbever use `set_if` = true inside the Icinga Configuration or Director Baskets. This will result in the Icinga Director always flagging a certain object as modified.
> Fix: Config generator should not use set_if = true

- cache/framework_cache.psm1
- icinga-powershell-framework.psm1
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- templates/framework_cache.psm1.template
Prevents the Icinga for Windows framework to recursively import itself on first startup or after reseting the cache file.
> Fix: Recursive loop on first loading of Framework

- doc/100-General/10-Changelog.md
- lib/core/framework/Test-IcingaForWindowsMigration.psm1
Fixes the framework migration tasks which fails in case multiple versions of the framework are installed, printing warnings in case there is
Fixes #615
>  Fix: Framework migration error on multi framework installation

- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Pass -NoLogo and -NoProfile once, not -NoLogo twice.
> Get-IcingaCheckCommandConfig: fix copy&paste error

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/writers/Write-IcingaAgentApiConfig.psm1
Adds support for `Write-IcingaAgentApiConfig` function to configure the Icinga Agent TLS cipher list setting.
> Feature: Adds support to allow Agent cipher list configuration

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
- lib/core/installer/Install-Icinga.psm1
Adds support to set the flag `-NoSSLValidation` for Cmdlets `icinga` and `Install-Icinga`, to ignore errors on self-signed certificates within the environment.
Example:
```powershell
icinga -NoSSLValidation
```
Icinga Shell:
```powershell
icinga -Shell -NoSSLValidation
```
Fixes #640
> Feature: Adds support to ignore SSL errors on IMC, Shell and Installer

- doc/100-General/10-Changelog.md
- lib/apis/Register-IcingaDirectorSelfServiceHost.psm1
- lib/core/installer/Install-Icinga.psm1
- lib/core/installer/menu/installation/AdvancedEntries.psm1
- lib/core/installer/menu/installation/director/SelfServiceConfig.psm1
- lib/core/installer/tools/CustomConfig.psm1
- lib/core/installer/tools/SetValuesFromStep.psm1
This new feature allows to configure the Icinga Director Self-Service call during registration, by modifing the JSON-String. This will only apply to the first time registration of a host and is not modified again, unless the host and director keys for this specific host object are removed.
This works directly inside the IMC installation wizard as well as for the exported installation command or file.
By doing so, you can manually define the IP-Address with `address` key in your JSON as well as the display name of an object with `display_name`. Example:
```json
{ "address": "127.0.0.1", "display_name": "Example Host" }
```
The following constants are available inside the configuration:
`$ifw.hostaddress$`: Will use the default IP-Address automatically fetched from the system …
> Feature: Adds support to configure Director Self-Service config string

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Adds support to simply use `-RebuildCache` for
```powershell
icinga -RebuildCache;
```
or
```powershell
icinga -Shell -RebuildCache;
```
to generate a new cache file not only for the Framework (like before), but also for all installed components of Icinga for Windows.
This makes it easier for regular use and error handling, as users will not have to remember a different Cmdlet or use the `-DeveloperMode` to force Icinga for Windows to rebuild everything.
> Feature: Adds support for -RebuildCache flag on icinga cmd to rebuild component cache

- doc/100-General/10-Changelog.md
- lib/core/repository/New-IcingaRepository.psm1
- lib/core/repository/New-IcingaRepositoryFile.psm1
- lib/core/repository/Sync-IcingaRepository.psm1
- lib/core/repository/Update-IcingaRepository.psm1
Instead of writing every file processed within the console output, we now use the progress bar handling to provide a better idea on how many files have been processed during a sync and update.
In addition, creating new repositories will now give an overview on how many files have been processed so far including the remaining files, instead of waiting for the shell to complete the task without any output.
> Feature: Adds progress bar to repository interaction instead of text output

- doc/100-General/10-Changelog.md
- lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
- lib/icinga/exception/Exit-IcingaThrowException.psm1
Fixes error and exception handling while using API-Checks, which now will in most cases always return a proper check-result object and also abort while running into plugin execution errors, in case a server is not reachable by the time sync plugin as example.
> Fix: Error and exception handling over API checks

- doc/100-General/10-Changelog.md
- lib/daemons/modules/ApiChecks/Invoke-IcingaApiChecksRESTCall.psm1
Fixes REST-Api to allow arguments with and without leading `-`
> Fix: REST-Api to allow args with and without leading -

- doc/100-General/10-Changelog.md
- lib/core/tools/Test-IcingaForWindowsCmdletLoader.psm1
- lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
- lib/provider/core/Get-IcingaProviderData.psm1
- lib/provider/core/Get-IcingaProviderElement.psm1
- lib/provider/core/New-IcingaProviderObject.psm1
Adds new base handling for future data providers with first metrics for `CPU` information
> Feature: Adds new plugin data provider handling and cpu data

- doc/100-General/10-Changelog.md
- icinga-powershell-framework.psm1
Adds support to run command `icinga` with new argument `-NoNewInstance`, to use `-RebuildCache` as example to update the current PowerShell instance with all applied changes, instead of create a new shell instance.
Does not support the argument `-DeveloperMode` in the same call, as Icinga for Window is dependent on these files for the current session.
Fixes #573
> Feature: Adds support to not load a new PowerShell instance for command icinga

- doc/100-General/10-Changelog.md
- lib/core/repository/Sync-IcingaRepository.psm1
Fixes `Sync-IcingaRepository` which did not save the SSH user and host inside the repository configuration, preventing `Update-IcingaRepository` to work properly and added missing scp progress
Fixes #611
> Fix: Sync-IcingaRepository not saving SSH settings

- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
Useful in case someone renames the commands in Director.
Otherwise, in this case, all commands would be broken with ifw-api as vars.ifw_api_command defaults to $command.name$.
**Unless** a specific command could inherit/import another specific command, I see no problems with this.
> Get-IcingaCheckCommandConfig: set vars.ifw_api_command in all commands

- doc/100-General/10-Changelog.md
- lib/core/docs/Add-IcingaDocumentContent.psm1
- lib/core/docs/New-IcingaDocumentObject.psm1
- lib/core/docs/Write-IcingaDocumentFile.psm1
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- lib/core/framework/Publish-IcingaPluginDocumentation.psm1
Adds new feature to write document content easier by storing it in memory first and then allowing to write it to disk at once with proper UTF8 encoding
New cmdlets:
* New-IcingaDocumentObject
* Add-IcingaDocumentContent
* Write-IcingaDocumentFile
> Feature: Adds new feature to write documents easier

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/manage/shell/StartIcingaShell.psm1
- lib/core/installer/tools/Clear-CLIConsole.psm1
- lib/core/installer/tools/ShowInstallerMenu.psm1
- lib/icinga/plugin/Write-IcingaPluginOutput.psm1
Fixes an issue with `Clear-Host` which could cause an exception during certain automation tasks, causing it to fail
> Fix: Clear-Host throwing exceptions during automation tasks

- doc/100-General/10-Changelog.md
- lib/core/repository/Update-Icinga.psm1
Fixes `Update-Icinga` not updating to the latest available version for a component and specifying `-Version` is updating to the latest one instead of the given one instead
> Fix: Update-Icinga not updating to latest or specified version

- doc/100-General/10-Changelog.md
- lib/core/repository/Update-Icinga.psm1
Fixes JEA-Profiles always being updated during `Update-Icinga` calls, even when no component or non JEA related components were updated
> Fix: JEA profile always modified during update process

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/installer/Install-IcingaAgent.psm1
- lib/core/icingaagent/installer/Uninstall-IcingaAgent.psm1
- lib/core/repository/Install-IcingaComponent.psm1
Fixes Icinga Agent installation and uninstallation, which could cause unintended automatic reboots
> Fix: MsiExec should not cause automatic host reboot

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Fixes JEA profile compiler not including REST-Api configuration during first installation
Fixes #664
> Fix: JEA installer not including REST-Api on first run

- lib/core/repository/Install-IcingaComponent.psm1
- lib/core/repository/Update-Icinga.psm1
Ensures the backwards compatibility with Icinga for Windows v1.11.0, which broke the update mechanism for version checks.
> Fix: Update compatibility with Icinga for Windows v1.11.0

- doc/100-General/10-Changelog.md
- lib/core/framework/Read-IcingaWindowsEventLog.psm1
- lib/core/tools/Show-IcingaEventLogAnalysis.psm1
- lib/provider/assets/hyperv/Get-IcingaProviderDataValuesHyperV.psm1
Fixes a memory leak while fetching Windows EventLog information by using CLI tools and inside the Hyper-V provide
> Fix: Memory leak in EventLog fetcher

- doc/100-General/10-Changelog.md
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes exception in some cases, when provider or metrics return values as `null` instead of `0` while units are being used for check objects.
This affects the Process plugin as one example
> Fix: Null value exceptions on checks with units

- doc/100-General/10-Changelog.md
- lib/core/jea/Get-IcingaJEAServicePid.psm1
- lib/core/windows/Restart-IcingaWindowsService.psm1
- lib/core/windows/Stop-IcingaJEAProcess.psm1
Fixes an issue while trying to stop the JEA process in certain cases, which results in an error during installation but has no other effect on the environment
> Fix: Exceptions in certain cases while trying to stop the JEA process

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/installer/Install-IcingaAgentCertificates.psm1
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Fixes Icinga for Windows port handling on installation, which will now use the proper defined port for communicating with the Icinga CA
Fixes #687
> Fix: Icinga CA port handling on installation

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaCheckCommandConfig.psm1
> Get-IcingaCheckCommandConfig: move -C from every single command to template

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/manage/framework/ToogleFrameworkApiChecks.psm1
- lib/core/jea/Install-IcingaJeaProfile.psm1
- lib/core/wintasks/daemon/Register-TaskRenewCertificate.psm1
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/eventlog/Register-IcingaEventLogMessagesRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsCertificateThreadTaskInstance.psm1
- lib/daemons/RestAPI/threads/Start-IcingaForWindowsCertificateThreadTask.psm1
Adds automatic renewal of the `icingaforwindows.pfx` certificate for the REST-Api daemon in case the certificate is not yet present, valid or changed during the runtime of the daemon while also making the `icingaforwindows.pfx` mandatory for all installations, regardless of JEA being used or not
Fixes #632
> Feature: Adds renewal handling for Icinga for Windows certificate

- doc/100-General/10-Changelog.md
- lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
On uncommon system configurations (number of sockets > 1) the TotalLoad perfdata of Invoke-IcingaCheckCpu was to high due to it being just summed up over all sockets.
This patch changes this computation, the load weighted by the number of sockets is summed up and then divided by the total number of CPUs.
> Sum up TotalLoad over all CPUs and divide it by number of threads

- doc/100-General/01-Upgrading.md
- doc/100-General/10-Changelog.md
- doc/100-General/20-Eventlog.md
- doc/110-Installation/05-Background-Daemons.md
- doc/110-Installation/06-Collect-Metrics-over-Time.md
- doc/110-Installation/30-API-Check-Forwarder.md
- doc/900-Developer-Guide/10-Custom-Daemons.md
- doc/900-Developer-Guide/12-Custom-API-Endpoints.md
- doc/knowledgebase/IWKB000005.md
- doc/knowledgebase/IWKB000014.md
- lib/core/framework/Install-IcingaForWindowsService.psm1
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/manage/framework/ToogleFrameworkApiChecks.psm1
- lib/core/installer/menu/manage/settings/services/ManageServices.psm1
- lib/core/logging/Icinga_EventLog_Enums.psm1
- lib/core/repository/Update-Icinga.psm1
- lib/core/windows/Install-IcingaSecurity.psm1
- lib/core/windows/Install-IcingaServiceUser.psm1
- lib/core/windows/Restart-IcingaWindowsService.psm1
- lib/core/windows/Uninstall-IcingaServiceUser.psm1
- lib/core/windows/Update-IcingaServiceUser.psm1
- lib/core/wintasks/Invoke-IcingaWindowsScheduledTask.psm1
Renames `Restart-IcingaWindowsService` to `Restart-IcingaForWindows` and adds alias for backwards compatibility to start unifying the Icinga for Windows cmdlets
> Feature: Renames "Restart-IcingaWindowsService" to "Restart-IcingaForWindows" and adds alias for backwards compatibility

- doc/100-General/10-Changelog.md
- lib/core/windows/Restart-Icinga.psm1
Adds new command `Restart-Icinga` to restart both, the Icinga Agent and Icinga for Windows
> Feature: Adds new command `Restart-Icinga` to restart both, the Icinga Agent and Icinga for Windows

- doc/100-General/10-Changelog.md
- lib/core/installer/menu/installation/director/DirectorTemplate.psm1
Fixes an issue with Icinga Director Self-Service API, which ignored the defined service user and didn't apply it to the configuration
> Fix: Icinga Director Self-Service API is ignoring service user

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/logging/Register-IcingaEventLog.psm1
Fixes size of the `Icinga for Windows` eventlog by setting it to `20MiB`, allowing to store more events before they are overwritten
> Fix: Size of Icinga for Windows eventlog

- doc/100-General/10-Changelog.md
- lib/core/icingaagent/setters/Set-IcingaServiceEnvironment.psm1
- lib/core/logging/Register-IcingaEventLog.psm1
Fixes various console errors while running Icinga for Windows outside of an administrative shell
> Fix: Errors for non-admin shells introduced with v1.12.0

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
- lib/core/installer/menu/manage/framework/ToogleFrameworkApiChecks.psm1
- lib/core/installer/menu/manage/settings/troubleshooting/Troubleshooting.psm1
- lib/core/jea/Install-IcingaJeaProfile.psm1
Fixes Icinga for Windows certificate creation while using WinRM or SSH for remote connections
> Fix: icingaforwindows.pfx creation over WinRM and SSH

- doc/100-General/10-Changelog.md
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/eventlog/Register-IcingaEventLogMessagesRESTApi.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsCertificateThreadTaskInstance.psm1
Fixes Icinga for Windows REST-Api which fails during certificate auth handling while running as `NT Authority\NetworkService`
> Fix: REST-Api not available while running as "NT Authority\NetworkService"

- doc/100-General/10-Changelog.md
- lib/daemon/Set-IcingaForWindowsThreadAlive.psm1
- lib/daemon/Suspend-IcingaForWindowsFrozenThreads.psm1
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/daemons/RestAPI/threads/Get-IcingaNextRESTApiThreadId.psm1
- lib/daemons/RestAPI/threads/New-IcingaForWindowsRESTThread.psm1
- lib/daemons/ServiceCheckDaemon/daemon/Add-IcingaServiceCheckDaemon.psm1
- lib/webserver/Icinga_HTTPResponse_Enums.psm1
- lib/webserver/Read-IcingaRESTMessage.psm1
- lib/webserver/Read-IcingaTCPStream.psm1
Fixes Icinga for Windows REST-Api to fully read client data, even when they client is sending the packets on a very slow basis, preventing the API trying to process an incomplete request
Fixes #672
> Fix: Icinga for Windows API should properly read network streams even for slow clients

- doc/100-General/10-Changelog.md
- lib/core/repository/Update-Icinga.psm1
Fixes the order for updating components with `Update-Icinga`, to ensure the `framework` is always updated first before all other components
> Fix: Update order for components to always update the framework first

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/wintasks/daemon/Register-TaskRenewCertificate.psm1
Fixes certificate handling for renewing certificates with the scheduled task background, which could fail on some Windows Server 2022 environments
> Fix: Icinga for Windows certificate handling for all Windows environments

- doc/100-General/10-Changelog.md
- lib/webserver/ConvertTo-IcingaX509Certificate.psm1
Fixes `icingaforwindows.pfx` creation in case another `certutil` is installed on the system and being available in the `PATH` environment
Fixes #724
> Fix: Usage of wrong certutil if present in PATH instead of system32 binary

- doc/100-General/10-Changelog.md
- lib/core/repository/Get-IcingaForWindowsServiceData.psm1
Fixes leading `\` for the service binary path and directory, which results in wrong behavior while using the same shell on which the initial installation was made
Fixes #722
> Fix: Leading backslash for service binary on initial setup

- doc/100-General/10-Changelog.md
- lib/daemons/RestAPI/daemon/New-IcingaForWindowsRESTApi.psm1
- lib/webserver/New-IcingaSSLStream.psm1
Adds support for both, TLS1.2 and TLS1.3 while also improving the response of the API for initial startup, by redirecting all calls to thread 0 if not all threads are loaded
> Feature: Adds support to TLS1.3 and improves startup response

- doc/100-General/10-Changelog.md
- lib/daemon/Start-IcingaPowerShellDaemon.psm1
Fixes a scenario on which a JEA service could become orphaned while manually stopping the Icinga for Windows service, without gracefully shutting down JEA.
Fixes #734
> Fix: JEA service could become orphaned and cause high CPU load

- doc/100-General/10-Changelog.md
- lib/core/repository/Update-Icinga.psm1
Fixes `Update-Icinga` to print an error in case a component is not installed, instead of silently continue
Fixes #729
> Fix: Update-Icinga to print an error in case a component is not installed

- doc/100-General/10-Changelog.md
- lib/provider/assets/cpu/Get-IcingaProviderDataValuesCpu.psm1
- lib/provider/assets/cpu/New-IcingaProviderFilterDataCpu.psm1
Adds support for the CPU provider to limit the CPU usage to 100% for each thread
> Feature: Adds option to CPU provider to limit thread usage to 100%

- doc/100-General/10-Changelog.md
- lib/core/installer/tools/Get-FileEncoding.psm1
- lib/core/tools/Read-IcingaFileSecure.psm1
Adds support to check the encoding of files to ensure we can properly load them and throw errors for unsupported encoding
> Feature: Adds support to check encoding of files

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/icingaagent/misc/Start-IcingaAgentInstallWizard.psm1
- lib/core/icingaagent/writers/Write-IcingaAgentEventLogConfig.psm1
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Adds cmdlet `Write-IcingaAgentEventLogConfig` to update eventlog severity and defaults to `warning`during installation and migration tasks while updating to Icinga for Windows v1.13.0
Fixes #711
> Feature: Adds cmdlet `Write-IcingaAgentEventLogConfig` to update eventlog severity and defaults to `warning`during installation and migration

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaServices.psm1
- lib/core/tools/Test-IcingaArrayFilter.psm1
- lib/icinga/exception/Icinga_IcingaExceptionEnums.psm1
Fixes an issue for service provider with service names not interpreted correctly in case it contains `[]`
This fixes https://github.com/Icinga/icinga-powershell-plugins/issues/398
> Fix: Service provider for brackets in service names

- doc/100-General/10-Changelog.md
- lib/webserver/New-IcingaTCPClientRESTMessage.psm1
Rationale: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Server
```
> GET /v1/checker?command=cpu HTTP/1.1
> Host: 10.27.0.147:5668
> User-Agent: curl/8.6.0
> Accept: */*
>
< HTTP/1.1 200 Ok
< Server: IcingaForWindows/1.12.3
< Content-Type: application/json
< Content-Length: 427
<
```
> REST API: in the Server header, identify the software, not the machine

- doc/100-General/10-Changelog.md
- lib/core/perfcounter/New-IcingaPerformanceCounterObject.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes an issue with performance counters, sometimes reporting empty values instead of at least 0
Fixes #746
> Fix: Performance counter results sometimes reporting null instead of 0

- doc/100-General/10-Changelog.md
- jobs/SetProcessPriority.ps1
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/windows/Restart-IcingaWindowsService.psm1
- lib/core/wintasks/daemon/Register-TaskIcingaForWindowsProcessPriority.psm1
- lib/core/wintasks/daemon/Start-TaskSetProcessPriority.psm1
Adds feature to set process priority for Icinga for Windows to BelowNormal for improved Host performance
> Feature: Sets Icinga for Windows processes to BelowNormal

- doc/100-General/10-Changelog.md
- lib/core/framework/Install-IcingaForWindowsService.psm1
- lib/core/framework/Install-IcingaFrameworkUpdate.psm1
- lib/core/framework/Invoke-IcingaForWindowsMigration.psm1
- lib/core/framework/Uninstall-IcingaForWindowsService.psm1
- lib/core/installer/menu/manage/settings/services/ManageServices.psm1
- lib/core/jea/Deny-IcingaJEACommand.psm1
- lib/core/repository/Install-IcingaComponent.psm1
- lib/core/windows/Restart-Icinga.psm1
- lib/core/windows/Restart-IcingaWindowsService.psm1
- lib/core/windows/Start-Icinga.psm1
- lib/core/windows/Start-IcingaForWindows.psm1
- lib/core/windows/Stop-Icinga.psm1
- lib/core/windows/Stop-IcingaWindowsService.psm1
- lib/core/windows/Uninstall-IcingaServiceUser.psm1
Adds new Cmdlets `Start-Icinga`, `Stop-Icinga`, `Start-IcingaForWindows` and `Stop-IcingaForWindows` in addition to the existing Cmdlets `Restart-Icinga` and `Restart-IcingaForWindows`
> Feature: Adds new start and stop Cmdlets for Icinga

- doc/100-General/10-Changelog.md
- lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1
This commit sets the maximum duration for cached data for service daemons to the proper amount.
Previously it was multiplied by 60, probably a typo from a time when the assigned value was in minutes and not in seconds directly.
Therefore the value was 60 times to high which leads to a massive amount of cached data which drags down the performance significantly.
> Set maximum cache duration for service daemons to the right value

- doc/100-General/10-Changelog.md
- lib/core/framework/New-IcingaEnvironmentVariable.psm1
- lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
- lib/daemons/ServiceCheckDaemon/tools/New-IcingaServiceCheckDaemonEnvironment.psm1
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1
- lib/icinga/plugin/ConvertTo-IcingaMetricsOverTime.psm1
- lib/icinga/plugin/Get-IcingaMetricsOverTimePerfData.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
- lib/icinga/plugin/New-IcingaCheckBaseObject.psm1
- lib/icinga/plugin/New-IcingaCheckResult.psm1
- lib/icinga/plugin/Write-IcingaPluginPerfData.psm1
This adds new and improved handling for Metrics over Time.
The overall execution time for the background tasks has been reduced, while also the memory management is way more efficient.
In addition to the improved core handling of the feature, performance metrics for metrics over time will NO LONGER BE WRITTEN.
This will increase the performance of the graphing solutions like InfluxDB a lot, while the monitoring by using the "-ThresholdInterval" argument is still possible.
```powershell
PS> Invoke-IcingaCheckCPU -Warning '5%' -ThresholdInterval '10m';
[WARNING] CPU Load [WARNING] Overall Load, Socket #0
\_ [WARNING] Overall Load: Value 6.546175% is greater than threshold 5% (10m Avg.) 
\_ [WARNING] Socket #0 
\_ [WARNING] Core 0: Value 18.391566% is greater than threshold 5% (10m Avg.) 
\_ …
```
> Feature: Adds new Metric over Time handling

- doc/100-General/10-Changelog.md
- lib/core/framework/Invoke-IcingaInternalServiceCall.psm1
Fixes EventLog error handling by no longer parsing command arguments to ensure passwords are not stored on the EventLog, unless the debug mode of Icinga for Windows is enable
Fixes #754
> Fix: Passwords being written as plain text in EventLog on error

- doc/100-General/10-Changelog.md
- lib/core/windows/Enable-IcingaServiceRecovery.psm1
Adds argument `-IntervalInSeconds` for `Enable-IcingaServiceRecovery` to allow setting a custom time interval for the service to restart, while setting the default to 120 seconds (2 minutes)
Fixes #766
> Feature: Improves service recover by adjustable restart time interval argument

- doc/100-General/10-Changelog.md
- jobs/GetWindowsService.ps1
Fixes test commands like `Test-IcingaForWindows` failing because of wrong assigned ServiceData information.
Fixes #778
> Fix: Test commands failing because wrong assigned service data

- doc/100-General/10-Changelog.md
- lib/core/repository/Install-IcingaComponent.psm1
Fixes the return value in case the `Agent` component could not be installed from `$FALSE` to `null`
> Fix: Return value for "Agent" component installation failure

- doc/100-General/90-Roadmap.md
Hey Christian,
there has been a pretty substantial blogpost purge on icinga.com - and now the linked posts from here are no longer available.
I changed the links to refer to the GitHub releases, not sure if this is what you want here, but I felt like this was the closest thing :)
> Change broken icinga.com/blog links to GitHub release links

- doc/100-General/10-Changelog.md
- lib/core/tools/ConvertTo-IcingaUnixTime.psm1
- lib/core/tools/Get-IcingaUnixTimeOffsetNow.psm1
- lib/icinga/plugin/Compare-IcingaPluginThresholds.psm1
- lib/icinga/plugin/Compare-IcingaPluginValueToThreshold.psm1
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes an issue with the new check handling, which did not properly convert values from checks to the correct performance data values and base values in some cases
Fixes #798
Fixes #796
> Fix: Wrong performance data values on unit conversion

- doc/100-General/10-Changelog.md
- lib/daemons/ServiceCheckDaemon/task/Add-IcingaServiceCheckTask.psm1
Fixes plugins throwing `UNKNOWN` in case `-TresholdInterval` is used for Metrics over Time, when checks are newly registered and checked, before the first MoT is executed and collected
Fixes #797
> Fix: UNKNOWN on checks using MoT thresholds if they are newly registered

- doc/100-General/10-Changelog.md
- lib/core/installer/Start-IcingaForWindowsInstallation.psm1
Fixes Icinga for Windows installer to always force the installation of the service, to ensure it is present
Fixes #786
> Fix: Icinga for Windows installer to always force service installation

- doc/100-General/10-Changelog.md
- lib/icinga/plugin/New-IcingaCheck.psm1
Fixes Icinga for Windows threshold comparison which wrongly compared warning/critical thresholds for non-range values (like Match)
Fixes #784
> Fix: Threshold comparison to only apply for ranged values

- doc/100-General/10-Changelog.md
- lib/core/tools/Get-IcingaServices.psm1
Fixes Icinga for Windows being stuck during installation while fetching service information over CIM-Instances, if other services are frozen, blocking the CIM-Request
Fixes #781
> Fix: Icinga for Windows being stuck while fetching service information if other services block CIM requests

- doc/100-General/10-Changelog.md
- lib/webserver/Disable-IcingaUntrustedCertificateValidation.psm1
Adds support to suppress messages for Disable-IcingaUntrustedCertificateValidation
> Feature: Adds support to suppress messages for Disable-IcingaUntrustedCertificateValidation

- doc/100-General/10-Changelog.md
- lib/icinga/plugin/New-IcingaCheckPackage.psm1
Fixes plugin compiler not handling `AddSummaryHeader` properly for nested check packages, not adding any check information
```powershell
[WARNING] CPU Load [WARNING] Socket #0 (All must be [OK])
\_ [OK] Overall Load: 8.283808%
\_ [WARNING] Socket #0: 2 Warning 3 Ok [WARNING] Core 0, Core 2 (All must be [OK])
\_ [WARNING] Core 0: Value 18.86168% is greater than threshold 9%
\_ [OK] Core 1: 4.852731%
\_ [WARNING] Core 2: Value 9.340026% is greater than threshold 9%
\_ [OK] Core 3: 0.080795%
\_ [OK] Core Total: 8.283808%
| totalload::ifw_cpu::load=8.283808%;9;;0;100 0_0::ifw_cpu::load=18.86168%;9;;0;100 0_1::ifw_cpu::load=4.852731%;9;;0;100 0_2::ifw_cpu::load=9.340026%;9;;0;100 0_3::ifw_cpu::load=0.080795%;9;;0;100 0_total::ifw_cpu::load=8.283808%;9;;0;100
```
Fixes #809
> Fix: AddSummaryHeader not adding any check information to check package

- doc/100-General/10-Changelog.md
- lib/core/tools/Test-IcingaAddTypeExist.psm1
Fixes a possible crash for `Test-IcingaAddTypeExist`, causing the Icinga for Windows installation to fail when third party components are checked which are malfunctioning
> Fix: Possible crash on assembly fetching for third party assemblies

- doc/100-General/10-Changelog.md
- lib/core/windows/Get-IcingaRandomChars.psm1
Fixes random chars function to truly generate unpredictable character sequences and to replace `Get-Random` which is not entirely secure
> Fix: Improved security for random character generator
